### ISSUE TITLE
The node list is empty

### ISSUE THREAD

**Issue by frank-pian** [mysteriumnetwork/mysterium-vpn-desktop#104]
Win10
Version 3.8.1.0

![微信截图_20210312101629](https://user-images.githubusercontent.com/8214804/110881886-0cae3b00-831c-11eb-889f-19758447aae0.png)
[mysterium-node.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/6127168/mysterium-node.log)

**Comment by frank-pian** [comment]
The filter is set to arbitrary, and you can see the list.
Why is the connection quality missing?

![微信截图_20210312102737](https://user-images.githubusercontent.com/8214804/110882887-96123d00-831d-11eb-98f9-2f606089e70b.png)

**Comment by chompomonim** [comment]
This is not an issue of empty node list, but with quality oracle reporting "poor" quality for nodes and nodes filter is looking only for max quality.

**Comment by frank-pian** [comment]
> 
> 
> This is not an issue of empty node list, but with quality oracle reporting "poor" quality for nodes and nodes filter is looking only for max quality.

Is this a common problem?
I think this is the reason for the recent drop in revenue on the node, and the loss of a lot of users

**Comment by chompomonim** [comment]
This is problem for users in regions who have less sessions.

We have released new version of quality oracle which is showing node quality based on data from your region. But if some nodes were never used ( or were used not enough) in your region, then quality oracle has little data. App is filtering out such never used or unpopular nodes.

We're now working on fix for this problem. How to release update very soon.

**Comment by shlavik** [comment]
This is problem for unclear UI.
Seems to may be fixed with checkbox "quality any",
which disable "quality slider" if checked.

**Comment by frank-pian** [comment]
> 
> 
> This is problem for users in regions where there are less sessions.
> 
> We have released new version of quality oracle which is showing node quality based on data from your region. But if some nodes were never used ( or were used not enough) in your region, then quality oracle has little data. App is filtering out such never used or unpopular nodes.
> 
> We're now working on fix for this problem. How to release update very soon.

I see, thank you

**Comment by chompomonim** [comment]
It should work better in recent release (v3.8.2+) of desktop app.
