### ISSUE TITLE
"Oops, couldn't connect." 

### ISSUE THREAD

**Issue by BlueLahar** [mysteriumnetwork/mysterium-vpn-desktop#107]
I launched the app in Windows on a PC. I set the preferences: medium quality and highest prices per hour and GB; country selections: Canada and the US. I tried over 20 different connections and every single time, I got a message "Oops! couldn't connect. Try another provider?" What is the reason for this? I was unable to find a single provider that worked.

**Comment by chompomonim** [comment]
To debug your situation we would need more information.

- Version of app you're using.
- App logs (your can report them via interface in desktop app and post here report ID).
- Is this happening after fresh install or it was working previously?

**Comment by tadaskay** [comment]
Please attach full logs to the issue as described in https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logging
For windows that would be (3 locations - app, node and supervisor logs respectively):

%USERPROFILE%\AppData\Roaming\MysteriumVPN\logs\*.log
%USERPROFILE%\.mysterium\logs\mysterium-node.log
%PROGRAMDATA%\MystSupervisor\myst_supervisor.log

**Comment by chompomonim** [comment]
This is quite old issue. Fully reworked v5 of desktop app was released and this issue most probably is already fixed. Please open new one if it still remain after upgrading to newest version of desktop dVPN app.

**Comment by jitneyy** [comment]
ok
