### ISSUE TITLE
Instant crash on 10.15.3

### ISSUE THREAD

**Issue by HeroHann** [mysteriumnetwork/mysterium-vpn-desktop#11]
Hello,
the current Version: 0.30.0 Snapshot does seem to have some problems.
When opening on Catalina 10.15.3 the Icon is "grayed" out. When starting directly from the volume it crashes instantly.

Older Version: 0.14.3 has Problems connection to any Hosts.

Replicate:
Just Download the DMG and try to start Mysterium in any way.

**Comment by tadaskay** [comment]
Currently, it's not possible to start directly from the volume

**Comment by cvl** [comment]
Doesn't work for me either, as mentioned on https://github.com/mysteriumnetwork/mysterium-vpn-desktop/issues/9

On the first run I get in system.log
Apr  6 11:18:42 Samsung-Printer-320x CoreServicesUIAgent[51550]: error -1 while removing quarantine data on path /Applications/MysteriumVPN.app/Contents/Frameworks/QtCore.framework/QtCore
Apr  6 11:18:42 Samsung-Printer-320x CoreServicesUIAgent[51550]: error -1 while removing quarantine data on path /Applications/MysteriumVPN.app/Contents/Frameworks/QtCore.framework/Resources
Apr  6 11:18:42 Samsung-Printer-320x CoreServicesUIAgent[51550]: error -1 while removing quarantine data on path /Applications/MysteriumVPN.app/Contents/Frameworks/QtCore.framework/Versions/Current
Apr  6 11:18:42 Samsung-Printer-320x CoreServicesUIAgent[51550]: error -1 while removing quarantine data on path /Applications/MysteriumVPN.app/Contents/Frameworks/QtDBus.framework/QtDBus
Apr  6 11:18:42 Samsung-Printer-320x CoreServicesUIAgent[51550]: error -1 while removing quarantine data on path /Applications/MysteriumVPN.app/Contents/Frameworks/QtDBus.framework/Resources
Apr  6 11:18:42 Samsung-Printer-320x CoreServicesUIAgent[51550]: error -1 while removing quarantine data on path /Applications/MysteriumVPN.app/Contents/Frameworks/QtDBus.framework/Versions/Current
Apr  6 11:18:42 Samsung-Printer-320x CoreServicesUIAgent[51550]: error -1 while removing quarantine data on path /Applications/MysteriumVPN.app/Contents/Frameworks/QtGui.framework/QtGui
Apr  6 11:18:42 Samsung-Printer-320x CoreServicesUIAgent[51550]: error -1 while removing quarantine data on path /Applications/MysteriumVPN.app/Contents/Frameworks/QtGui.framework/Resources
Apr  6 11:18:42 Samsung-Printer-320x CoreServicesUIAgent[51550]: error -1 while removing quarantine data on path /Applications/MysteriumVPN.app/Contents/Frameworks/QtGui.framework/Versions/Current
Apr  6 11:18:42 Samsung-Printer-320x CoreServicesUIAgent[51550]: error -1 while removing quarantine data on path /Applications/MysteriumVPN.app/Contents/Frameworks/QtPrintSupport.framework/QtPrintSupport
Apr  6 11:18:42 Samsung-Printer-320x CoreServicesUIAgent[51550]: error -1 while removing quarantine data on path /Applications/MysteriumVPN.app/Contents/Frameworks/QtPrintSupport.framework/Resources
Apr  6 11:18:42 Samsung-Printer-320x CoreServicesUIAgent[51550]: error -1 while removing quarantine data on path /Applications/MysteriumVPN.app/Contents/Frameworks/QtPrintSupport.framework/Versions/Current
Apr  6 11:18:42 Samsung-Printer-320x CoreServicesUIAgent[51550]: error -1 while removing quarantine data on path /Applications/MysteriumVPN.app/Contents/Frameworks/QtWidgets.framework/QtWidgets
Apr  6 11:18:42 Samsung-Printer-320x CoreServicesUIAgent[51550]: error -1 while removing quarantine data on path /Applications/MysteriumVPN.app/Contents/Frameworks/QtWidgets.framework/Resources
Apr  6 11:18:42 Samsung-Printer-320x CoreServicesUIAgent[51550]: error -1 while removing quarantine data on path /Applications/MysteriumVPN.app/Contents/Frameworks/QtWidgets.framework/Versions/Current

On subsequent runs I get:
Apr  6 11:22:44 Samsung-Printer-320x com.apple.xpc.launchd[1] (network.mysterium.mysterium-vpn-desktop.183072[26821]): Service exited with abnormal code: 1

The app crashes instantly.

**Comment by chompomonim** [comment]
It should work with running app after moving .dmg into the Applications folder. Have you tried that?

**Comment by HeroHann** [comment]
You can’t open the application “MysteriumVPN” because it may be damaged or incomplete.

[https://siasky.net/7ABMj10X4g90PXKceUGGuPwp3fWEMKQfhFXp7sIkBW2qyA](url)

**Comment by tadaskay** [comment]
Since the app is not signed, it could be an issue with the macOS Gatekeeper. Can you check if _Security & Privacy_ allows apps from **Anywhere**?

![Screenshot 2020-04-06 at 17 14 23](https://user-images.githubusercontent.com/4745368/78568071-43392700-782a-11ea-8e71-ac5eb69dd129.png)

**Comment by HeroHann** [comment]
SAME problem. No change if from image, applications-folder or desktop.

**Comment by cvl** [comment]
Mac 10.11.6 (El Capitan):

If I run qode in terminal, I get more specific error:

Samsung-Printer-320x:MacOs cl$ ./qode 
internal/modules/cjs/loader.js:1201
  return process.dlopen(module, path.toNamespacedPath(filename));
                 ^

Error: dlopen(/Applications/MysteriumVPN.app/Contents/Resources/dist/nodegui_core-140b99686eee4785d7b5f11d2364be36.node, 1): Symbol not found: _OBJC_CLASS_$_MTLCaptureManager
  Referenced from: /Applications/MysteriumVPN.app/Contents/Resources/dist/../../Frameworks/QtGui.framework/Versions/5/QtGui (which was built for Mac OS X 10.13)
  Expected in: /System/Library/Frameworks/Metal.framework/Versions/A/Metal
 in /Applications/MysteriumVPN.app/Contents/Resources/dist/../../Frameworks/QtGui.framework/Versions/5/QtGui
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1201:18)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1040:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Applications/MysteriumVPN.app/Contents/Resources/dist/index.js:23:7903)
    at n (/Applications/MysteriumVPN.app/Contents/Resources/dist/index.js:1:110)
    at Object.<anonymous> (/Applications/MysteriumVPN.app/Contents/Resources/dist/index.js:1:1870)
    at n (/Applications/MysteriumVPN.app/Contents/Resources/dist/index.js:1:110)
    at Object.<anonymous> (/Applications/MysteriumVPN.app/Contents/Resources/dist/index.js:1:8881

**Comment by cvl** [comment]
Managed to run it after upgrading to 10.15.4

It still throws
Apr  7 19:17:16 Samsung-Printer-320x com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.qode.2305): Failed to bootstrap path: path = /Applications/MysteriumVPN.app/Contents/MacOS/qode, error = 2: No such file or directory

But that seems to have no effect.

**Comment by cvl** [comment]
@HeroHann although I'm not from Mysterium, I'd suggest to run the ./Applications/MysteriumVPN.app/Contents/MacOS/qode in your Terminal and see if you get any errors.

**Comment by HeroHann** [comment]
Contents/MacOs/qode ; exit;
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by HeroHann** [comment]
Maybe the Dev can put a new release with the most recent changes so we can test...

**Comment by tadaskay** [comment]
Please checkout the latest master 996c6bfd8a36b9ba624b8f7e10444dccaf8634bc and see if the issue persists. If yes, please join us at discord and let's discuss https://discordapp.com/invite/n3vtSwc

**Comment by tadaskay** [comment]
Also updated dev snapshot https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/download/SNAPSHOT/MysteriumVPN.1.0.dmg

**Comment by HeroHann** [comment]
Working like a charm once over to the application folder. I would like to have it on the desktop but I can live with it. Good job!

**Comment by chompomonim** [comment]
So, can we close this issue? @HeroHann
