### ISSUE TITLE
Mysterium app starts up but doesn't load anything

### ISSUE THREAD

**Issue by etherunit** [mysteriumnetwork/mysterium-vpn-desktop#111]
Mysterium starts up but doesn't load anything. Says: "Starting Daemon" and wheel keeps spinning in the center of the screen. Running Windows 8 w/ 4 mb ram. It was running fine several months ago but not anymore.

It was uninstalled and re-installed many times since then in order to attempt to make it work. That didn't help. 

Logfile: 
[mysterium-node (2).log.zip](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/6362695/mysterium-node.2.log.zip)

**Comment by mwadle** [comment]
After an update it works on my machine.
