### ISSUE TITLE
Ship AppImage

### ISSUE THREAD

**Issue by talentlessguy** [mysteriumnetwork/mysterium-vpn-desktop#113]
for universal Linux support would be great to have AppImage to be abel to easily install Mysterum on any other system than Debian/Ubuntu

**Comment by talentlessguy** [comment]
bump

**Comment by talentlessguy** [comment]
not stale

**Comment by shlavik** [comment]
prioritise this issue please!

**Comment by shlavik** [comment]
not stale!
