### ISSUE TITLE
Update info.plist to use mysterium.desktpo instead of nodegui and myapp

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/mysterium-vpn-desktop#13]
https://github.com/mysteriumnetwork/mysterium-vpn-desktop/blob/f3375ab82457d793d9e9f88cb322e28f7a5d51b3/deploy/darwin/MysteriumVPN.app/Contents/Info.plist#L10

In `info.plist` there are set nodegui values instead of Mysterium.

**Comment by chompomonim** [comment]
It would be better to create issues with an action type of naming, not a question. Changing description of tasks.

**Comment by tadaskay** [comment]
This is a valid issue, but this will have to wait until proper signing is implemented to see if it doesn't cause any issues with signing the `qode` executable within the app.

**Comment by cvl** [comment]
@tadaskay could you share info.plist you're using to build? It doesn't work for my app with current version in repo.

**Comment by chompomonim** [comment]
I do believe @tadaskay is using same `info.plist` you can find in repo.

**Comment by cvl** [comment]
It's different, because even in your build info.plist is different than in his build.

**Comment by tadaskay** [comment]
Fixed in e6bf74d26819d2c768544577a6c68b6d35f14e2f
