### ISSUE TITLE
Severe reduction in traffic for hosted nodes following most recent update.

### ISSUE THREAD

**Issue by sj64** [mysteriumnetwork/mysterium-vpn-desktop#148]
Like many others I have noticed a near complete drop off in traffic to my hosted node since the latest updates.

I discovered that the show residential ips only option is set by default in the desktop client settings, and clearing that allowed me to find my server. As this is neither transparent, nor flagged up to the user during install - it is likely the most obvious reason for the drop off in traffic, as most users will not notice this silent removal of hosted nodes like mine, when they update to the newest client.

It would be a simple matter to change the default to show all nodes. Or if preferred, offer the user the choice during installation. As it is, hosted nodes like mine are being unfairly penalised with regard to the bounty system, as well as reducing choice for end-users.

**Comment by tadaskay** [comment]
Hosted nodes do not unblock media streaming services and therefore don't provide good UX for the end-users. For that, residential has been selected by default. This will change in the 5.x version with the upcoming filter presets: "Media streaming", "Browsing", etc.

**Comment by cvl** [comment]
Sounds like self-canibalizing decision.
It's relatively rare for services to block hosting nodes, and if that's the case, user can easily switch to residential.
On the other hand, losing hosting nodes is something you won't get back easily if ever.

**Comment by sj64** [comment]
Not all nodes are equal! Mine has 200Mb/s per port up and down, so theoretically enough for 40 simultaneous HD video streams, or even 8 @ 4K. Perhaps there is a way to evaluate speeds as part of the regular 1.2GB test? Then show this in the Quality icon by each node, rather than a blanket ban?
