### ISSUE TITLE
Built app quits automatically on the first run

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/mysterium-vpn-desktop#15]
No error logs.

From Console activity:

default    10:39:55.629678+0300    lsd    - 45683955: Checking whether application is managed at file:///Applications/Portals.app/network.portals.desktopvpn
default    10:39:55.651276+0300    dmd    Received xpc stream event (distributed notification matching) with name: com.apple.LaunchServices.applicationRegistered user info: {
    bundleIDs =     (
        "network.portals.desktopvpn"
    );
    isPlaceholder = 0;
}
default    10:39:55.663078+0300    Finder    LAUNCHING:0x0-0x31f31f Portals foreground=1 bringForward=1 seed=482 userActivityCount=0
default    10:39:55.731476+0300    loginwindow    -[PersistentAppsSupport applicationReady:] | App: Portals, ready, updating active tracking timer
default    10:39:55.731559+0300    loginwindow    -[ApplicationManager checkInAppContext:eventData:] | ApplicationManager: Checked in app : Portals
default    10:39:55.798943+0300    distnoted    register name: com.apple.sharedfilelist.change object: com.apple.LSSharedFileList.ApplicationRecentDocuments/network.portals.desktopvpn token: f43e5 pid: 459
default    10:39:59.339948+0300    lsd    - 45683955: Checking whether application is managed at file:///Applications/Portals.app//network.portals.desktopvpn
default    10:39:59.360125+0300    dmd    Received xpc stream event (distributed notification matching) with name: com.apple.LaunchServices.applicationRegistered user info: {
    bundleIDs =     (
        "network.portals.desktopvpn"
    );
    isPlaceholder = 0;
}
default    10:39:59.373599+0300    loginwindow    -[PersistentAppsSupport applicationQuit:] | for app:Portals, _appTrackingState = 2
default    10:39:59.373631+0300    loginwindow    -[PersistentAppsSupport applicationQuit:] | App: Portals, quit, updating active tracking timer

**Comment by cvl** [comment]
Note, that Mysterium app release https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases behaves the same

**Comment by cvl** [comment]
To make it easier to reproduce (didn't try otherwise), clean up the former installation first:

1. remove Mysterium app, empty the trash
2. sudo rm -r ~/.mysterium
2. STOP DAEMON:
* Set keepalive flag to false in network.mysterium.myst_supervisor.plist:
    * sudo nano -w /Library/LaunchDaemons/network.mysterium.myst_supervisor.plist
* sudo launchctl unload /Library/LaunchDaemons/network.mysterium.myst_supervisor.plist && sudo rm /Library/LaunchDaemons/network.mysterium.myst_supervisor.plist
* then kill the process from activity monitor (if it still exists)

**Comment by tadaskay** [comment]
The following is a proper way to remove the app, supervisor and workdirs

```
sudo rm -rf /Applications/MysteriumVPN.app
sudo launchctl unload /Library/LaunchDaemons/network.mysterium.myst_supervisor.plist
sudo rm /Library/LaunchDaemons/network.mysterium.myst_supervisor.plist
sudo rm -rf /var/root/.mysterium ~/.mysterium
```

**Comment by cvl** [comment]
thanks!

**Comment by tadaskay** [comment]
Built app quits automatically on the first run is because of the way Catalina handles app security notarization. You can verify that from console logs:

```
Error checking with notarization daemon: 3
```

If you notarize the application using [guidelines](https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution), that supposedly will not happen.

More information: https://eclecticlight.co/2019/10/10/how-catalina-handles-app-first-run/

**Comment by tadaskay** [comment]
Closing this for now, consult apple docs for further information
https://developer.apple.com/documentation/xcode/notarizing_macos_software_before_distribution

**Comment by cvl** [comment]
The app is notarised.

**Comment by cvl** [comment]
You can try Portals app by yourself: https://www.portals.network/download/portals-mac/?wpdmdl=6765&refresh=5e95d173151c51586876787
