### ISSUE TITLE
[feature request] Linux packages for non-debian-based systems

### ISSUE THREAD

**Issue by maxreuben** [mysteriumnetwork/mysterium-vpn-desktop#152]
**Is your feature request related to a problem? Please describe.**
No way to install on non-debian Linux systems

**Describe the solution you'd like**
A package for other non-debian based systems like Fedora, Arch etc.

**Additional context**
Not being able to connect to my favorite VPN on my Fedora desktop is a disappointment. It's quite easy to package the app to alternate OSes and I'd be willing to do it myself.

**Comment by chompomonim** [comment]
In next release of desktop app there will be also .rpm available to download and install.
