### ISSUE TITLE
Faulty installation on Windows

### ISSUE THREAD

**Issue by bpound** [mysteriumnetwork/mysterium-vpn-desktop#153]
I uninstalled the client, rebooted, reinstalled the client (the latest 4.2.1 version on an up-to-date windows machine), and now it doesn't work. As in, I double click on the icon that was created during installation and nothing happens (other than spawning a myst_supervisor service, but _it_ doesn't seem to be doing anything). If I run C:\Program Files\MysteriumVPN\resources\static\bin\myst.exe, it does pop up command line stuff but I don't really know the syntax well enough to run anything and test the installation from here.

I don't have any log folder in %USERPROFILE%\AppData\Roaming\MysteriumVPN or the .mysterium folder in %USERPROFILE%, but the myst_supervisor log is here: 
[myst_supervisor.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/6766406/myst_supervisor.log)

**Comment by tadaskay** [comment]
Thanks for reporting this! As I don't have enough data to debug this, would you be able to help by getting on our [discord server ](https://discordapp.com/invite/n3vtSwc) and pinging me @tadaskay so we can work this out?

**Comment by tadaskay** [comment]
Resolved offline; by upgrading to [5.0.0-5](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases)
