### ISSUE TITLE
Fresh app doesn't connect to nodes or connects strangely

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/mysterium-vpn-desktop#16]
Fresh app => app on first run. Subsequent runs don't produce the same behavior.

- It fails to connect to the same nodes which actually work on subsequent runs.
- Fails to connect to most nodes (works on subsequent runs).
- Even if it connects, it disconnects after 10 seconds or so
- Some nodes work okay though even on the first run

No errors visible, but in myst_supervisor.log I constantly get these:

2020/04/14 17:15:33 Running myst supervisor daemon
2020/04/14 17:15:33 Waiting for connections...
2020/04/14 17:15:33 Waiting for connections...
2020/04/14 17:15:33 Client connected: unix
2020/04/14 17:15:33 myst [err=exec: already started] output: 
2020/04/14 17:15:33 Error running myst: exec: already started
2020/04/14 17:22:35 Client disconnected: unix
2020/04/14 17:22:40 Waiting for connections...
2020/04/14 17:22:40 Client connected: unix
2020/04/14 17:22:40 myst [err=exec: already started] output: 
2020/04/14 17:22:40 Error running myst: exec: already started

**Comment by tadaskay** [comment]
`exec: already started` means exactly that - you have a conflicting instance of node running on your machine. Close it (kill it) and it will work just fine.

**Comment by cvl** [comment]
No, it was clean run.

I've tried with Mysterium v1.0 release https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/download/SNAPSHOT/MysteriumVPN.1.0.dmg

Same behavior.

Doesn't connect to the node. After I relaunch the app, it works.

Try this proposal:

0xa790b42ed41898122fb485c79267cdcf53482412 | GB | openvpn

**Comment by tadaskay** [comment]
I hope you understand that this is in active development and things are expected to break often. it's clearly written in the readme. Contributions are welcome. 😎

**Comment by cvl** [comment]
I hope you understand that I'm building business on this app, I'm not playing around.

Please talk to @chompomonim

**Comment by cvl** [comment]
Also, that open source project is in active development is not a reason to close issues without resolving them.

**Comment by cvl** [comment]
Created issue on node project, as I guess it's node problem: https://github.com/mysteriumnetwork/node/issues/2051

**Comment by tadaskay** [comment]
It's great that you are building on the foundation of our apps and platform. But let's get one thing straight - this is an open-source project. You're welcome and free to use the source, modify it and adapt it to your needs, but ultimately I don't own you anything. If you continue to communicate in an aggressive manner and make demands, your rights will be limited.

**Comment by cvl** [comment]
I'll create issues in node project from now on.

**Comment by chompomonim** [comment]
node v0.30.0-pre which is used in this desktop app build is not very stable. It's pre-release and there are a couple of problems to fix. I think if you would try to connect into same node via CLI it would also not work :(

We're fixing issues with this pre-release and should release a stable version (or at least another, more stable pre-release) until the end of this week. I do believe that a desktop app will also work more stable then.

**Comment by cvl** [comment]
The strange thing here is that this occurs only on the first run (and the most important one for new customers), the subsequent runs works really well.
