### ISSUE TITLE
Linux version of desktop app

### ISSUE THREAD

**Issue by wuniversales** [mysteriumnetwork/mysterium-vpn-desktop#17]
Please add Linux compatibility.

**Comment by chompomonim** [comment]
Yes, this is on our roadmap. But first, we'd like to release MacOS and Windows versions as most of the users are requesting apps for these platforms.

**Comment by dpellegr** [comment]
Following the instruction in the README and I managed to build the code on Linux. I can also launch the app and I get a windows with the Mysterium graphics and a loading prompt. But then it just keeps printing

```Connecting to the supervisor...```

to the terminal, without moving any further. Is this expected?

**Comment by chompomonim** [comment]
@dpellegr supervisor is still not ported to Linux. That is a reason why we don't have official Linux desktop app.
On Linux you can try using `myst cli`.

**Comment by dpellegr** [comment]
> On Linux you can try using `myst cli`.

Oh, this looks very cool!

I had some issues understanding what it is and how to use it. So basically it comes together with the node. You fire it up and then interact with it through the http requests documented here: https://tequilapi.mysterium.network/

Am I right?

PS. I may want to run the node natively, dropping the docker container...

**Comment by chompomonim** [comment]
Yes, you're correct. `myst cli` comes together with node. Node can work in consumer and in provider modes and both modes can be controlled via cli. CLI communicates with node via tequilla api.

**Comment by arpitjindal97** [comment]
I'm having hard time using `myst cli` . My use case is I want to connect to a Myst node just like a normal Desktop app

**Comment by chompomonim** [comment]
@arpitjindal97 cli improvements are in our backlog for October!

**Comment by merlinjk** [comment]
Hi is it possible to use myst cli as client and not nodes on linux / docker ?

**Comment by dpellegr** [comment]
> Hi is it possible to use myst cli as client and not nodes on linux / docker ?

Sure! Instead of running `/usr/bin/myst service` (which is to run a node providing your connection to the network) use `/usr/bin/myst daemon` to just boot up the node without any activity. Then myst cli commands will be available to register a new identity (only once), unlock it and connect to a provider.

Here is a full command stack example:

    /usr/bin/myst --config-dir=/etc/mysterium-node --data-dir=/var/lib/mysterium-node --runtime-dir=/var/run/mysterium-node --keystore.lightweight --agreed-terms-and-conditions daemon

Then in another terminal:

    /usr/bin/myst cli identities unlock $MY_IDENTITY
    /usr/bin/myst cli connect $MY_IDENTITY $PROPOSAL wireguard

Check `/usr/bin/myst cli help` to see how to register the new identity and how to obtain the proposal list.

**Comment by merlinjk** [comment]
did you know why i don't get the same proposal as windows client ? like if i filter the proposal list on only residential i have nothing and i have only 95 proposal without filters , and when i check whindows their is 200 residential ^^

**Comment by merlinjk** [comment]
and i get this error when im trying to connect 
2021-01-07T21:37:06.507 ERR tequilapi/client/http_client.go:109      >  error="Put http://127.0.0.1:4050/connection: dial tcp 0.0.0.0:0->127.0.0.1:4050: connect: connection re

**Comment by chompomonim** [comment]
> Hi is it possible to use myst cli as client and not nodes on linux / docker ?

@merlinjk check this guide: https://docs.mysterium.network/user-guide/

Please make sure that you're using v0.41.0+ (you can get it from `ppa:mysteriumnetwork/node-pre`)

**Comment by chompomonim** [comment]
Now anyone can download `.deb` package with Linux client.
https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/latest
