### ISSUE TITLE
App is stuck on launching node. "Starting Daemon"

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/mysterium-vpn-desktop#170]
**Describe the bug**
Few VPN users on windows are experiencing and issue where their app is stuck on launching mode and app is not starting. 

**To Reproduce**
1. Open the app on windows
2. Wait for app to open
3. See launching screen loading stuck 

**Expected behavior**
After launching screen loads, the app should normally start.
![لقطة الشاشة 2021-08-01 213822](https://user-images.githubusercontent.com/84313603/127978250-bb58ce5c-cf12-4ebc-83b8-bec83d215852.png)

**Logs**
Attach logs (app, node, supervisor) to the issue. Where to find the logs: https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logging
![لقطة الشاشة 2021-08-02 032435](https://user-images.githubusercontent.com/84313603/127978435-150c317c-6974-4994-9a5a-9b33512b772b.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - App Version Latest

**Additional context**
Already tried:

1)Deleting and reinstalling app.

2)Deleting the app logs from a user folder?
Windows
%USERPROFILE%\AppData\Roaming\MysteriumVPN\logs (app)

**Comment by jitneyy** [comment]
same it wont work for me
