### ISSUE TITLE
[bug] Mysterium VPN topup 

### ISSUE THREAD

**Issue by Sundarvs** [mysteriumnetwork/mysterium-vpn-desktop#173]
**Describe the bug*

I use Mysterium VPN for windows. I recently made a top up using my cryptocurrency USDT from currency.com account to Wallet ID. The top up value selected was for 49.39 USDT. However, I transferred 30 USDT to this wallet since my currency.com site auto set value as 30.  I opted for the payment through browser option and copied the ID and pasted in my currency.com USDT's withdraw option to pay. I got confirmation from Currency.com that transaction was successful. Till date the topup value is not reflecting in my Mystt account in PC.  Payment transaction screen shot attached. 

**To Reproduce**
2. Click on '.
3. See error

**Expected behavior**

**Logs**
Attach logs (app, node, supervisor) to the issue. Where to find the logs: https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logs

**Screenshots**

![06C35CFE-5918-442D-8DB7-8D8F22E47078](https://user-images.githubusercontent.com/88760950/128972654-af730331-26e3-4a17-9ffb-709169884d7f.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - App Version [e.g. 4.1.0]

**Additional context**

**Comment by tadaskay** [comment]
Thanks for reporting! We're looking into your case and will get back to you soon.

**Comment by tomasmik** [comment]
Hi, in this case we can offer two options for you:
* A full refund for the money you've sent. Should take up to 48hours to refund the funds.
* A partial deposit of myst. We can send you MYST for the 30USDT that we've received.

Please let me know how you want to proceed. In case you want to continue with the refund, it would be great if you provided me with an email address where I can send a refund form for you to fill.

**Comment by Sundarvs** [comment]
Thank you for your response.

Could you please arrange for the full refund.  You can send me the refund
form to this email address.  ***@***.***

Thank you very much

Regards
Sundar

**Comment by tomasmik** [comment]
> Could you please arrange for the full refund.  You can send me the refund
form to this email address.  ***@***.***

Sorry but the email address was filtered out. Not sure why..

**Comment by Sundarvs** [comment]
Hi

It is the same email address that you are using. ***@***.***

Regards
Sundar

**Comment by tomasmik** [comment]
Again sorry but the email address is not shown for me. Try contacting support by going to: https://my.mysterium.network
You'll see a chat bubble appear on the bottom left side of the webpage, click that and write about the issue.
If not email me at `tomasm@mysterium.network` with your node identity.

**Comment by tomasmik** [comment]
From what I gather support has sent you a message.

**Comment by Sundarvs** [comment]
Thank You Tomas,  I will get back to you at the earliest.

regards
Sundar
