### ISSUE TITLE
[bug] Country list filter does not work

### ISSUE THREAD

**Issue by creotiv** [mysteriumnetwork/mysterium-vpn-desktop#177]
**Describe the bug**
When trying to filter countries by name got empty list, while country exist in the list.

**To Reproduce**
1. Open app
2. Look at the list some country
3. start typing it's name

**Expected behavior**
When typing text into country name filter it should list countries with such text in the name

**Logs**
App logs clear without errors

**Screenshots**
![Screenshot from 2021-08-16 14-04-45](https://user-images.githubusercontent.com/250125/129555122-d6f64d64-a90c-472b-8ea9-d3d64f3ce7be.png)
![Screenshot from 2021-08-16 14-04-33](https://user-images.githubusercontent.com/250125/129555127-f47b5228-4869-4256-83fd-0d3cbbbe33bc.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - App Version: 4.2.1

**Comment by chompomonim** [comment]
I see that you're using older version of dVPN app. Could you try v5.0.2?
You can download it here: https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/tag/5.0.2
