### ISSUE TITLE
App balance didn't change after topup

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/mysterium-vpn-desktop#178]
**Describe the bug**
I have sent MYSTT into payment channel address. Hermes sees balance correctly but app's user interface is still showing zero.

**To Reproduce**
1. Send a lot of data to spent almost all your balance
2. When balance is < 0.1 MYSTT sent some token's to topup your app.
3. Connection is still staying active and all works as expected but app is showing **0** instead of **2.9** MYSTT

<img width="1369" alt="Screenshot 2021-08-17 at 02 44 16" src="https://user-images.githubusercontent.com/153896/129642791-fa9ea0d4-71dd-4206-bb01-b02a3ff320ad.png">

**Desktop:**
 - OS: macOS 11.4
 - App Version: 5.0.2

**Comment by chompomonim** [comment]
Balance didn't updated even after using CoinGate's payments. 

1. Go to app's wallet and choose to topup 20 tokens
2. Choose BTC (via Lightning Network) and pay invoice which app will show
3. See message about successful payment.
4. Check payment channel on Hermes and blockchain, see that tokens are already there (https://mumbai.polygonscan.com/token/0xb923b52b60e247e34f9afe6b3fa5accbaea829e8?a=0x5E39027940c652264A8690078e8eeF048Aa384A9). 
5. Check app's balance and find zeros there again.

**Comment by chompomonim** [comment]
What is even worse, after stopping VPN session you can't establish new one :(

<img width="752" alt="Screenshot 2021-08-17 at 03 06 23" src="https://user-images.githubusercontent.com/153896/129643904-3b7491cc-5a8e-434c-a961-71469aaba7c6.png">

**Comment by chompomonim** [comment]
After app's restart app finally is showing balance correctly.

<img width="752" alt="Screenshot 2021-08-17 at 03 08 04" src="https://user-images.githubusercontent.com/153896/129644023-25483199-2710-46e3-9df5-55e7bd8ab072.png">

**Comment by tadaskay** [comment]
This is obviously a node issue, app simply displays the balance from the node's state.

**Comment by tomasmik** [comment]
This is probably something to do with how we no longer listen to events on chain and periodically query event funcs. I assume it takes time to get an update fast enough now.

**Comment by tomasmik** [comment]
Got more reports from people which sort of confirm that this is an issue with the new desktop app. Could you please investigate a bit further and see if you'e missed something with the rework @tadaskay

**Comment by chompomonim** [comment]
@tomasmik this issue is on testnet3 and on testnet2.
