### ISSUE TITLE
Add possibility to direct on-chain (using Polygon) topup with MYST, MATIC or other tokens

### ISSUE THREAD

**Issue by chompomonim** [mysteriumnetwork/mysterium-vpn-desktop#182]
**Is your feature request related to a problem? Please describe.**

At the moment for any topup users should use CoinGate integration and are not able to topup directly into their payment channel. I believe on mainnet there should be easy to use interface for direct topup (avoiding 3rd parties).

**Describe the solution you'd like**
1. Topup user interface should allow to choose "direct payment on Polygon" (similar to how they choose "Lightning network" for Bitcoin). In such case instead of CoinGate generated ethereum address, people should see user's payment channel address on Polygon.
2. Add MATIC with similar checkbox as above. Also setup payment channel so MATIC sent to it would automatically swapped to MYST using Quick swap.
3. Create "direct topup" website which would allow to topup with any token listed on QuickSwap. You simply enter identity address you'd like to topup and website is generating special transaction which would swap that tokens into MYST and would send them to app's payment channel. User would need to have installed Metamask and hold tokens on Polygon.

That are my current ideas which could allow to avoid using 3rd party to topup and would still allow resonable user experience. 

**Additional context**

This is feedback from one of beta testers about his topup experience:

> During topup - issue with only method to topup using imbedded coinbank link api generated. For anonymous topup is impossible with third party. Also - no fee for network shown so no way to know cost to use third party not affiliated with.

> I tried BTC, BTC lightning, ETH all using same process flow - so gave up.

> Note: If using mobile app to topup, the form only presents user with the QR or a copy to clipboard for the coinbank invoice link with timer. Q: If user only has one phone - how are they going to scan it with their wallet address? I had to install MetaMask on mobile (Android - Samsung s9+ test unit) and sync wallets to then attempt again within browser by opening the presented coinbase link and then manually entering ETH to send. This is WAY too long a process to go mainstream if you ask me - then there is no confirmation or info on network fee. I trued to use a wallet for ETH with $20 in it or there about and it said insuficient funds even for 20 mystt (I had .96 or so on wallet in app already).

> I also tried with BTC but again no option to check fees. Not worth $10 or more transaction fee to add $7 of mystt. Tried again with lightning network enabled and again locked into the same process flow.

> It is nice to see simple api use to return info back but I feel it is injecting dependency on third party (even trusted) that need not be there. Any way to integrate swap in-app with link to osmosis like or gravity or allow direct lightning contract connections with mobile app and linked lightning... anyhow - I did not complete top-up as result. Will grab other phone and send BTC from other account but not excited about spending that much in transaction fee and waiting around forever for confirmation and still not knowing how coinbank is storing or using our data - terms of service no shown and no info on how they use data or track or otherwise... very concerned with abstracting away payment gateway when we have an amazing decentralized privacy focused app to begin with.

> So, sadly, this said I could not topup to over 1MYST so I quit the test there. If my spouse wants to loan me some ETH from her account on her phone I will try again later.

**Comment by GoZippy** [comment]
What can I do to help?

**Comment by GoZippy** [comment]
Please also check coinbank api for call to display cost estimates for third party fees.

**Comment by sj64** [comment]
Just to add that a simple, low/zero gas topup interface will be a make or break feature for Mysterium. I have >60 MYST in my Brave inbuilt wallet (based on Metamask I think). To transfer say 10 Myst (currently about $5) to my dVPN desktop app, running on the exact same laptop; ie from one running app to another on the same machine - costs $32 in transfer fees. This is ludicrously out of proportion.

Frankly no idea of what is involved in integrating a polygon dApp - but just want to add my thumbsup for this feature. Such a promising weapon in the coming times deserves no less.

**Comment by chompomonim** [comment]
The first part (possibility to topup polygon MYST) of this epic will be done for upcoming mainnet release, see #211
