### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by CHINLEX** [mysteriumnetwork/mysterium-vpn-desktop#195]
I am literally unable to load into mysterium it is always stuck at loading when i create new and just doesnt work when i click import, 
![image](https://user-images.githubusercontent.com/90084735/132085232-dead68eb-92c1-4cef-b02f-2ff9fffe63bc.png)
It literally says loading forever here are my logs 
[renderer.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/7109319/renderer.log)
[main.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/7109320/main.log)
please fix this issue i need to use this vpn for the consistent residential ips but cant and i have like 25 myst

**Comment by tadaskay** [comment]
Hi, thanks for reporting the issue.

1. Regarding import scenario, from the logs it is clear that you are importing not an identity backup file. To import an identity, use a file that has been saved through the backup option in the app.
```
[2021-09-03 23:16:11.180] [info]  Spawning a child process:  C:\Program Files\MysteriumVPN\resources\static\bin\myst.exe cli --agreed-terms-and-conditions --tequilapi.port=44050 identities import ** C:\Users\CHINLEX\.mysterium\keystore\remember.json
[2021-09-03 23:16:16.047] [info]  [31m[ERROR] [0mFailed to import identity: server response invalid: 400 Bad Request (http://127.0.0.1:44050/identities-import). Possible error: failed to import identity: version not supported: 0
```

2. It's hard to say why the identity creation fails without looking at actual logs (note you only attached the app logs). https://github.com/mysteriumnetwork/mysterium-vpn-desktop#windows 
3. If you had a previously working identity before then you should not probably be looking into creating a new one. Could you contact me on discord `@tadaskay `? Or run these cmds from the app directory:
```
./static/bin/myst cli --tequilapi.port 44050
```
```
identities list
```
Then for each of the identities in the list, do:
```
identities balance <id>
```
Paste the output of all the above here.

**Comment by tadaskay** [comment]
Fixed by importing an exported ID file
