### ISSUE TITLE
[bug] Doesn't automatically reconnect after hibernation (Windows 10, client 6.3.0)

### ISSUE THREAD

**Issue by shlavik** [mysteriumnetwork/mysterium-vpn-desktop#200]
If you put the computer to sleep during a connected VPN session, then after waking up, the client (6.3.0) shows that the connection is active, but in fact there is no connection, disconnect button does not work.
Client version 6.0.0 successfully reconnected to the node after hibernation, and consequently degradation occurred.

**To Reproduce**
1. Connect to some node in mysterium client 6.3.0 on laptop with windows 10
2. Turn the laptop to sleep by pressing hardware power button
3. Wake up the laptop after hibernation

**Expected behavior**
Automaticaly reconnection to same node like before hibernation.
Client show actual connection status.

**Comment by shlavik** [comment]
Just checked how client working at last commit version, cannot reproduce bug, so issue closed.
But version 6.3.0 bugged anyway.

**Comment by shlavik** [comment]
Client version 6.7.0 -- bug reproduce, so issue reopened

**Comment by shlavik** [comment]
Client version 6.8.0 (Windows 10) -- bug reproduced

**Comment by cvl** [comment]
Very important bug.

**Comment by shlavik** [comment]
Not stale! The application just stop worked at this situation, have to kill the process in the task manager!

**Comment by shlavik** [comment]
Client version 10.4.1 -- bug reproduced
