### ISSUE TITLE
DNS_PROBE_FINISHED_NO_INTERNET

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/mysterium-vpn-desktop#212]
**Describe the bug**
Issue is happening on windows desktop app on the latest (mainnet) version 

**Logs**
[mysterium-node-22.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/7591736/mysterium-node-22.log)

**Comment by googlegame** [comment]
same issue

**Comment by tadaskay** [comment]
Could you try the latest version https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/tag/10.0.2 ?
