### ISSUE TITLE
List of nodes changes randomly every few seconds[bug]

### ISSUE THREAD

**Issue by dkarasev1** [mysteriumnetwork/mysterium-vpn-desktop#217]
**Describe the bug**
List of available nods to connect changes randomly each 5-10 seconds, showing 10 to 100 random available connections.

**Logs**
[main.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/7598329/main.log)
[renderer.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/7598330/renderer.log)
[renderer.old.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/7598331/renderer.old.log)
[mysterium-node.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/7598336/mysterium-node.log)
[myst_supervisor.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/7598392/myst_supervisor.log)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 10.0.2

**Comment by RuizPerezS** [comment]
Hi mate, I have the same problem, did you solve it?
