### ISSUE TITLE
Update our docs. MYST can't be found on Bittrex?

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/mysterium-vpn-desktop#219]
**Is your feature request related to a problem? Please describe.**

We may need to update our doc. MYST can't be found on Bittrex?

https://bittrex.zendesk.com/hc/en-us/articles/115003977472-Pending-market-removals-01-26-2018

https://bittrex.zendesk.com/hc/en-us/articles/360025090091-Wallet-removal-on-04-12-2019

**Describe alternatives you've considered**

**Additional context**
Our current docs: https://docs.mysterium.network/node-runners/payout-guide/

*_USA blocked from HitBTC_

**Comment by otkd** [comment]
> We may need to update our doc. MYST can't be found on Bittrex?

Did you actually look?
https://global.bittrex.com/Market/Index?MarketName=USDT-MYST
https://global.bittrex.com/Market/Index?MarketName=BTC-MYST
