### ISSUE TITLE
Account-less payment system

### ISSUE THREAD

**Issue by Mahdi321** [mysteriumnetwork/mysterium-vpn-desktop#22]
I really disappointed when I saw the Portal app. For payments it asks for buying subscription account (A central and traceable method)
What I prefer for payment system is an in-build Monero wallet and payment per connection session directly to vpn provider. App developer paid in 2 ways directly by client app or can get paid by VPN providers for listing their server in its bootstrapping server. (it can still be in form of commission for attracting residential providers for this every connection session should have fixed time)

**Comment by chompomonim** [comment]
@Mahdi321 Portals is 3rd party application. This native mysterium dvpn is supporting only token payment method. Payments are done in p2p way (from consumer to provider) and are using 2nd layers solution (similar to Lightning Network). 

By my knowledge, there are no possibility to have fast and scalable payments for Monero and it is quite hard to build something similar to Lightning Network on top of Monero. Micropayments are essential for Mysterium, so, unfortunately, we can't look into Monero base currency for Mysterium.

From our whitepaper: 
"Considering the nature of a decentralized VPN network, one can assume that network participants would prefer to remain anonymous. Given the lack of trust, a service consumer will not be willing to pay a bigger amount up front. On the other end, the service provider isn’t willing to deliver service without prepayment. 

From this above mentioned scenario arises a need to split the service into chunks - provided in exchange for micropayments - meaning that each party risks a much smaller value. Put into context within a decentralized VPN network, this would mean that a user will pay a node a couple of times a minute, sending a tiny amount of tokens in exchange for the bandwidth they are renting."
