### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by AlexTechGR** [mysteriumnetwork/mysterium-vpn-desktop#224]
I encountered a bug when depositing money into the myst app: Money deposited, 0 myst
I donloaded the app, created an identity, topped up for 11.43 the payment failed from the side of the myst payment provider but went through on my side (revolut). I restarted the app and got into the panel with the vpn locations, however, 0 myst on the top.
![εικόνα](https://user-images.githubusercontent.com/50967021/143894380-d0731180-786d-4847-a312-eb79322b3709.png)

ID: 6c59ebe6-76ac-4f0f-b270-f1317e584be4
Address: 0xecdfe24c49971679bd86437eabbe9bdf203ac97c

**Comment by tadaskay** [comment]
@AlexTechGR Thanks for reporting this! So sorry that it didn't work out for you as intended. I was able to find and validate this transaction - it went through just fine, but our payment backend failed to update the order status. 

Would you like to receive MYST that you ordered addressed to the ID `0xecdfe24c49971679bd86437eabbe9bdf203ac97c` or a refund to your card?

**Comment by tadaskay** [comment]
I've issued a full refund
