### ISSUE TITLE
[bug] Add resolvconf dependency for linux packages

### ISSUE THREAD

**Issue by soffokl** [mysteriumnetwork/mysterium-vpn-desktop#225]
After installing application for Linux, DNS failed to be set as described in the https://github.com/mysteriumnetwork/node/issues/4320

The reason for this is missing dependency `resolvconf`. 

Manual install of the `resolvconf` solves the problem. 

Please add `resolvconf` as a required dependency to the package.

**Comment by cvl** [comment]
Does this fix work out of the box for end user, or he has to mingle with command line to fetch dependencies etc?

**Comment by vhp1360** [comment]
redhat releases hasn't resolvconf package.
how to solve it in redhat?
