### ISSUE TITLE
Top up with MYST: client does not indicate if this is with a Polygon or Ethereum address [bug]

### ISSUE THREAD

**Issue by MarkWieczorek** [mysteriumnetwork/mysterium-vpn-desktop#228]
**Describe the bug**
The mainnet client (macOS) has the option to top up with MYST. However, the client does not tell you whether you should send MYST to an Ethereum or Polygon address. Obviously, this is necessary to perform the transaction (unless both are accepted!).
<img width="637" alt="Screenshot 2021-12-02 at 22 52 19" src="https://user-images.githubusercontent.com/8697285/144509608-701273e8-070b-463c-a978-ca33945851c6.png">

**Comment by InfinityLoveWar** [comment]
It shows before but should be visible on the final payment processing site too.
![tzutzu](https://user-images.githubusercontent.com/95510348/144690037-36681075-ad24-40b1-8ae6-b2ede2d05615.png)

**Comment by MarkWieczorek** [comment]
This information does not show up on the macOS 10.0.2 release.

**Comment by tomasmik** [comment]
Update to 10.1.0 https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/tag/10.1.0
