### ISSUE TITLE
Create a noob friendly guide on how to properly back up keystore files

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/mysterium-vpn-desktop#234]
Is your feature request related to a problem? Please describe.

Lots of users are accidentally deleting their data cache and therefore deleting their keystore files.

Describe the solution you'd like
Create a noob friendly guide on how to properly back up keystore files and keep them safe. If possible, even set a default safe folder where files are stored, and clearly inform users that files are stored in there.

Describe alternatives you've considered
Make the process as crystal clear as possible and constantly remind them with notifications in app warning them to not delete their keystore files.

Create a noob friendly guide on documentation dedicated to dvpn users.

**Comment by Madlykeanu** [comment]
just put the file in google drive or some other cloud storage

**Comment by isaackielma** [comment]
Newest app version will force users to save their private keys in their device. The process should be quite straightforward. Users will certainly have a backup in their device.

This last version should help avoid the identity loss issue: https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/
