### ISSUE TITLE
My wallet doesn't show the correct amount of MYST [bug]

### ISSUE THREAD

**Issue by giu176** [mysteriumnetwork/mysterium-vpn-desktop#235]
I made a top up in August this year (20 MYST), at that time the operation was concluded correctly but now I can’t see my correct balance anymore, I barely used the vpn since then and I had my identity backed up on the cloud, no matter how many time I restore the identity the amount of MYST now is 0.98. I also had my ID connected to my smartphone and my laptop and I'm sure that the balance was correct also in the Android App but now my devices show the wrong amount of MYST. I'm sure that this summer I had something like 21 MYST on my account and I didn't use the vpn since then.

1. Go to 'Settings>Mysterium ID>Restore from Backup
2. Select my .json file
3. Insert my password
4. After the identity is restored the wallet shows 0.98 MYST.

I should have 20.98 MYST instead of 0.98 because I topped up 20 MYST in August when I had only 1 MYST on the account and since I used the vpn only a few times and for a very small periods of time for browsing it's reasonable that I've spent only 0.02 MYST. Now I want to use the vpn but my balance is wrong.

I lost my logs when I formatted my desktop pc few weeks ago. On my laptop (it's not the device I used for the top up) I have the logs dating back to few days after my transaction and they shows that I've imported the identity of my recent top up:

The day of the top up I back up the ID I had on the laptop because it contains a few MYST I didn't want to lose:
[2021-08-19 14:00:48.173] [info]  [32m[SUCCESS] [0mIdentity exported to file: C:\MY BACKUP PATH\Mysterium ID\Few Myst\LaptopIdentityNumber.json

Five days later I import the ID that I had on my desktop with the topped up wallet:
[2021-08-24 10:24:49.227] [info]  Spawning a child process:  C:\Program Files\MysteriumVPN\resources\static\bin\myst.exe cli --agreed-terms-and-conditions --tequilapi.port=44050 identities import MY PASSWORD 'C:\MY BACKUP PATH\Mysterium ID\ToppedUpIdentityNumber.json'
[2021-08-24 10:24:50.099] [info]  [32m[SUCCESS] [0mIdentity imported: ToppedUpIdentityNumber

 - Desktop PC OS: Windows 10
 - App Version 10.1.0
 
 - Laptop PC OS: Windows 11
 - App Version 10.1.0

- Smartphone OS: Android 10
- App Version 2.0.3.107120

In addition I have the summary of the transaction related to my top up in this link: https://www.blockchain.com/btc/tx/f8e21576937d7d1aa231e3f2d8a676195db8e6e152f3696534402738f037814e

**Comment by furkanarius** [comment]
Hi @giu176!

I'm sorry to hear this. We will work on this issue but to solve your problem, we'll deposit 21 MYST to you so you can continue to use Mysterium dVPN. Could you please share your ID with me so we can proceed? You can find it on your profile.

After I receive your ID, it'll take 2-3 weeks to deposit that amount and I'll let you know as soon as it's done. Thanks again for reporting this issue!

**Comment by giu176** [comment]
Hi, thanks for the quick response!

 

This is my ID: 0x5697fb85722d7ce318ecb26b7ae2c63719a82e8e

 

I really appreciate your efforts and the dvpn in general because it worked very well every time if it weren’t for this issue.

I also like your customer service.

 

Kind regards, 

Giulio.

**Comment by leo1in88** [comment]
me too, i got the same error. Tried to contact you guys but no reponse

**Comment by furkanarius** [comment]
Sorry to hear that @leo1in88. Could you please the transaction information so we can help you?
