### ISSUE TITLE
the payment is not reflected in app balance

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/mysterium-vpn-desktop#242]
**Describe the bug**
Hello, I installed the application on windows, I followed the steps and made a payment of 9.53 USD, the payment is reflected in my card but the app does not recognize me, what should I do?

<img width="784" alt="Screenshot 2021-12-31 at 05 39 02" src="https://user-images.githubusercontent.com/84313603/147798050-16bbf811-3b53-40b9-833b-489bcb543745.png">
<img width="773" alt="Screenshot 2021-12-31 at 05 39 44" src="https://user-images.githubusercontent.com/84313603/147798068-fcd72509-0a56-4ec9-aaa2-3de35489307e.png">

**Comment by tadaskay** [comment]
Try updating to the latest version - 10.3.

**Comment by FilterUnfiltered** [comment]
This issue still remains, it's practically a scam. Any payments made by card do not get added to your account and they still take the money. I was looking forward to using mysterium but the lack of attention to critical issues like this makes it a lot less promising, to say the least. This isn't even the first open issue I see with this specific issue...
