### ISSUE TITLE
I installed the latest version,when i start the apk massege open 'check your wifi conection' when i press retry it stuck on the screen plz fix this problem

### ISSUE THREAD

**Issue by ArefAgha** [mysteriumnetwork/mysterium-vpn-desktop#258]
I installed the latest version,when i start the apk message open 'check your wifi connection' when i press retry it stuck on the screen please fix this problem 
![Screenshot_20220109-014116](https://user-images.githubusercontent.com/97835341/149661358-54ae0a7e-7015-4e6b-9eb7-a9a570d8056b.png)
![Screenshot_20220109-014123](https://user-images.githubusercontent.com/97835341/149661363-10bd1d96-383a-46b9-b442-3dcd4fede76b.png)

**Comment by ArefAgha** [comment]
> **Describe the bug** A clear and concise description of what the bug is.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
>     1. Go to '...'
> 
>     2. Click on '....'
> 
>     3. See error
> 
> 
> **Expected behavior** A clear and concise description of what you expected to happen.
> 
> **Logs** Attach logs (app, node, supervisor) to the issue. Where to find the logs: https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logs
> 
> **Screenshots** If applicable, add screenshots to help explain your problem.
> 
> **Desktop (please complete the following information):**
> 
>     * OS: [e.g. Windows 10]
> 
>     * App Version [e.g. 4.1.0]
> 
> 
> **Additional context** Add any other context about the problem here.

I installed the latest version,when i start the apk massege open 'check your wifi conection' when i press retry it stuck on the screen plz fix this problem

**Comment by etherunit** [comment]
@ArefAgha Apologies for the delayed reply. Do you still experience this kind of problem?

**Comment by ArefAgha** [comment]
Yes its still stuck

**Comment by isaackielma** [comment]
Have you tried connecting via wifi at all?

**Comment by ArefAgha** [comment]
Yes via wifi and mobile data
