### ISSUE TITLE
Stuck on Registering Mysteriumid

### ISSUE THREAD

**Issue by ashutoshno120** [mysteriumnetwork/mysterium-vpn-desktop#262]
![image](https://user-images.githubusercontent.com/96180338/151675607-e1da818f-2223-4cc0-bec4-402bc3f49a4d.png)
![image](https://user-images.githubusercontent.com/96180338/151675621-29526bcf-5129-4bee-88c7-637b32a16202.png)
My new Mysterium id is stuck on that page its been 1 hour and it's still on the same page. what should i do now

**Comment by makedir** [comment]
same issue I just bought $2, money is booked on my cc, and now I am stuck with the above and nothing is happening.
