### ISSUE TITLE
Top up Failure

### ISSUE THREAD

**Issue by Wolfhartx** [mysteriumnetwork/mysterium-vpn-desktop#264]
Hello. Good day! I am using mysterium vpn on my android phone. I top up my account however upon paying, the myst did not enter my account. I used coins.ph to pay and used the bitcoin address provided by the team support in mysterium vpn. However up until now, the myst is still not in my account. 
![Screenshot_2022-01-31-08-29-53-050_network mysterium vpn](https://user-images.githubusercontent.com/98250232/151724524-0755ed43-454c-49bc-bf02-f1f1c2f731ff.jpg)
![Screenshot_2022-01-31-08-29-57-605_network mysterium vpn](https://user-images.githubusercontent.com/98250232/151724535-518166ea-e86b-45ed-8671-306ab3597c12.jpg)

**Comment by isaackielma** [comment]
Could you please provide us your coingate receipt to the top up transaction? Also your mysterium ID? That would be quite helpful for resolution of this issue.

**Comment by Wolfhartx** [comment]
I did not use coingate. I used coins.ph and the support team in mysterium
gave me a bitcoin address and that is where I sent the payment. Attach is
the proof. Here is my mysterium
id: 0xc64bd8c45f70c43659480ca5e0fc682fb0e9ea48

**Comment by Wolfhartx** [comment]
Are there any application I can use to top up my acc aside from coingate?

**Comment by isaackielma** [comment]
We partnered with coingate in order to handle our crypto payments. When you top up in the app there should be a receipt button so you can get the receipt from the payment.
