### ISSUE TITLE
Unknown location nodes

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/mysterium-vpn-desktop#265]
**Describe the bug**
on the app country list there are 3 nodes under "unknown"  country. Also another node under a separate "unknown" category

**Screenshots**
<img width="628" alt="Screenshot 2022-02-02 at 20 58 35" src="https://user-images.githubusercontent.com/84313603/152236512-d45d6e07-dffa-413e-a86f-908f24bc0e3c.png">

**Desktop (please complete the following information):**
 - OS: Mac
 - App Version 10.5.1

**Comment by tadaskay** [comment]
This is expected behavior when the location cannot be resolved.
