### ISSUE TITLE
Wrong invoice amount

### ISSUE THREAD

**Issue by Sermooh** [mysteriumnetwork/mysterium-vpn-desktop#279]
The application generates an invoice for the wrong amount in ETH and Myst (ETH) if you need to pay VAT. 

![2022-02-14 13-34-26](https://user-images.githubusercontent.com/96525149/153848129-e0869f89-ea8c-4742-8057-a8577bb65f34.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - App Version 10.5.1

**Comment by gir489** [comment]
Your real IP is shown in the screenshot. You might want to delete this.

**Comment by gir489** [comment]
![Untitled](https://user-images.githubusercontent.com/7742541/153910119-a7b3a532-f406-431b-a684-ecdc19941aaa.png)
This seems to be an issue exclusive to the Linux variant, I can't reproduce this issue.

**Comment by Sermooh** [comment]
> Your real IP is shown in the screenshot. You might want to delete this.

Thank you for your concern, but this is not my IP. I connected through a European country using another VPN to test VAT because other users were complaining. There is no VAT in my country.

**Comment by gir489** [comment]
WOW this app is buggy as hell! I was dicking around with the payments, and somehow this happened! It's supposed to be BTC
![Untitled](https://user-images.githubusercontent.com/7742541/153929521-a7cbfa6e-2708-4466-a22b-94e52372f23c.png)
!

**Comment by tadaskay** [comment]
VAT is calculated based on country so it works as expected. Just to clarify - no calculation of taxes or other order data is done on the client side.
