### ISSUE TITLE
[bug] was unable to establish a connection

### ISSUE THREAD

**Issue by AxlMoscow** [mysteriumnetwork/mysterium-vpn-desktop#288]
After updating 10.5.2 to 10.5.3 was unable to establish a connection through any node.

The problem solved by clearing folders:
C:\Users\*user*\AppData\Local\mysterium-vpn-desktop-updater
C:\Users\*user*\AppData\Roaming\MysteriumVPN
C:\Users\*user*\.mysterium
C:\ProgramData\MystSupervisor

**Desktop:**
 - OS: Windows 10 LTSB v 1607 (Build 14393.4946)
 - App Version 10.5.3
[main.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/8093153/main.log)
[renderer.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/8093154/renderer.log)
![2022-02-18_02h48_22](https://user-images.githubusercontent.com/38603703/154594896-352c9e97-b374-4a9e-a8db-146733e54965.png)

**Comment by gir489** [comment]
This was fixed in 10.5.4.

**Comment by Sermooh** [comment]
Version 10.5.4. doesn't exist yet )

**Comment by gir489** [comment]
I don't know, I fixed 10.5.2 by putting https://www.wintun.net/ into C:\WIndows\System32. Maybe that will work for you too? I feel like this app is built on duct tape and bailing wire.

**Comment by tadaskay** [comment]
Can't tell much without logs

**Comment by gir489** [comment]
The logs are in the OP.

**Comment by AxlMoscow** [comment]
> Can't tell much without logs

Logs are attached.
