### ISSUE TITLE
[bug] server list is empty

### ISSUE THREAD

**Issue by syahpian** [mysteriumnetwork/mysterium-vpn-desktop#290]
**Describe the bug**
server list is empty

**To Reproduce**
1. open dvpn app
2. server list empty

**Expected behavior**
server list should be populated my list of node online

**Logs**
Attach logs (app, node, supervisor) to the issue. Where to find the logs: https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logs
[renderer.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/8103600/renderer.log)
[main.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/8103597/main.log)

**Screenshots**

![image](https://user-images.githubusercontent.com/12189144/154833453-99915a2b-7cc5-4e60-b72f-097c5b56dc59.png)

![image](https://user-images.githubusercontent.com/12189144/154833459-98a54c02-80ee-4303-ac03-86203b1927c8.png)

**Desktop (please complete the following information):**
 - OS: windows 11
 - App Version: 10.5.3

**Additional context**

**Comment by gir489** [comment]
You cut off your MYST balance, do you have enough?
![image](https://user-images.githubusercontent.com/7742541/154861857-4b9c4aee-0ead-403c-8f62-dcacc5618099.png)
It's working for me.

**Comment by syahpian** [comment]
![image](https://user-images.githubusercontent.com/12189144/154863036-7bb6673b-8003-4555-afb5-2389c4c2ae68.png)

have 0.95 myst, enough for testing node speed

**Comment by tadaskay** [comment]
Can't tell without logs being attached, but looks like a simple network error

**Comment by gir489** [comment]
Um, he did include the logs though?

**Comment by syahpian** [comment]
yup, the log is there 

![image](https://user-images.githubusercontent.com/12189144/154910546-341a82ee-4f9b-41b3-9a68-18734852f077.png)

**Comment by gir489** [comment]
![giphy](https://user-images.githubusercontent.com/7742541/154910895-8105c2fd-ffe2-4999-b7da-12394ea51656.gif)

**Comment by tadaskay** [comment]
```
Writing response body failed error="write tcp 127.0.0.1:44050->127.0.0.1:16153: wsasend: An established connection was aborted by the software in your host machine."
```
This looks like an interference from a thirdparty app (could be firewall/antivirus or smth else)
