### ISSUE TITLE
[bug]Wrong address in metamask - my fault 

### ISSUE THREAD

**Issue by grafffu** [mysteriumnetwork/mysterium-vpn-desktop#298]
Hello,

Because it was stolen from my metamask on the ERC20 network .. 134 DAI... you have proof in the note below; .... In a hurry to save the coins/tokens from the other networks, I mistyped the recipient (copy-paste error) ... and I sent the only 7 myst  right in the contract of your project. 

https://polygonscan.com/tx/0x4ef661c7ac52ad84910aa5d2e564d90a748d14a1aca860a462b60a0d44ca0590

Can they be recovered somehow? 

Note:
Hacked Metamask:

https://etherscan.io/tx/0x92a19e548f670f9e31ab4ba6190de0cfd235d1fffc32cfe828cf29bcef169738

https://etherscan.io/tx/0x9920848bcfeb2e59042a2e0c1b3ebb277f7546b5e91089c3ef1abb03e3cdb02e

https://etherscan.io/tx/0x45a2b8b0770a56815de394474891d6407b94d598052658b288470d7f16bf84b8

Ty

**Comment by Yuxanju** [comment]
You will need to synchronize your Wallet and then you debug with bech13

**Comment by grafffu** [comment]
I don't know what "debug with bech13" means ... I just asked if the 7 MYSTs could be sent back (from MYST's contract address) to that Metamask address. Because the hacker doesn't know about them ... and I'll transfer them to my Ledger address then.

**Comment by Yuxanju** [comment]
I will send you a link from ellipal. You follow the link till you get to
debug and then you click on it .. let me know if you want me to send it now

**Comment by grafffu** [comment]
What is the purpose of that debugging?

**Comment by Yuxanju** [comment]
Debugging will help you rectify the issues with your wallet and block any
unauthorized transactions on your wallet

**Comment by Yuxanju** [comment]
You can only debug the wallet that you are using and can cover up for
0.0001 gas fee. It can’t work for an empty wallet or abandon wallet .. you
can synchronize the wallet you are using
This is the link
www.ellipalsuites.com

**Comment by grafffu** [comment]
I don't think I can handle ... where do I find that debug? (I have an Ellipal wallet - ... Metamask was hacked ... not my Ellipal ... )

**Comment by grafffu** [comment]
How may we help you?

Transaction Delay ?
Swap/Exchange Issues?
Missing Funds?
Other 

Should I use this tutorial? (second page ...)

**Comment by grafffu** [comment]
That site asks me for seed ... you realize I don't put any seed there ... even if the wallet is compromised now :)))))

**Comment by Yuxanju** [comment]
Click on other….the link is an ellipal encrypted secure link.. just follow
the steps.. everything is secure

**Comment by Yuxanju** [comment]
You can message ellipal to confirm .. it’s all good.. that’s just the best
way to secure and protect your wallet from hack and malware attacks
