### ISSUE TITLE
Unable to generate private key

### ISSUE THREAD

**Issue by Yethuzaw** [mysteriumnetwork/mysterium-vpn-desktop#299]
I accidentally deleted it and can not log in again
Unable to generate private key
Help make it reusable

**Comment by Yethuzaw** [comment]
![Screenshot_2022-03-01-08-29-26-648_cn.wps.moffice_eng.xiaomi.lite.jpg](https://user-images.githubusercontent.com/100663767/156108995-17dce129-361f-42b1-8059-c8e0cc5648a4.jpg)

**Comment by tadaskay** [comment]
Duplicate. See the answer in https://github.com/mysteriumnetwork/mysterium-vpn-desktop/issues/302
