### ISSUE TITLE
mysterium vpn

### ISSUE THREAD

**Issue by Yethuzaw** [mysteriumnetwork/mysterium-vpn-desktop#302]
I accidentally deleted it and can not log in again
Unable to generate private key
Help make it reusable
    

![Screenshot_2022-02-28-23-05-37-177_com.chrome.beta.jpg](https://user-images.githubusercontent.com/100663767/156131889-a136890e-ddfe-4dcb-9d38-5590d748bf01.jpg)

![Screenshot_2022-03-01-08-29-26-648_cn.wps.moffice_eng.xiaomi.lite.jpg](https://user-images.githubusercontent.com/100663767/156131919-7c8bd0c0-2940-4cc5-b2f5-031baa3159b5.jpg)

![Screenshot_2022-03-01-09-51-44-982_com.coinbase.android.jpg](https://user-images.githubusercontent.com/100663767/156131940-7a2a6f3c-60eb-4439-81b0-8ecb3264e7ae.jpg)

**Comment by tadaskay** [comment]
We are not managing your account, this is how decentralization works. If you delete your keys and don't have a backup, nothing can be done.
