### ISSUE TITLE
Some error occurred 'request cancelled while waiting for connection'

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/mysterium-vpn-desktop#304]
**Describe the bug**
Error message pop up upon opening the app

**Screenshots**
<img width="357" alt="Screenshot 2022-03-04 at 00 07 38" src="https://user-images.githubusercontent.com/84313603/156692072-759744bb-5220-4afb-a20f-3bb7004c5b7a.png">

**Comment by Moamen225200** [comment]
This problem took more than 3 days and I don't know the reason, even though my internet speed is high

**Comment by Moamen225200** [comment]
My account has 5$ balance
