### ISSUE TITLE
Payment failed - coingate order expired

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/mysterium-vpn-desktop#318]
![telegram-cloud-photo-size-2-5310169476420974608-x](https://user-images.githubusercontent.com/68943180/160107181-fbbef82b-9077-4799-9e4f-d5ae1f8d0913.jpg)
The payment was already done by the consumer, but coingate order is expired for some reason.

Coingate Order ID: https://pay.coingate.com/invoice/1610b5af-195e-4a5d-93a5-84dfd0fa74e9
MYST - Ethereum Mainnet transaction hash: https://etherscan.io/tx/0x29d02f13be73b01b1e257b0e4899a2636548ff43d0d143593a084ae2a97e7f70

**Comment by isaackielma** [comment]
Is this still an ongoing issue? I have talked with Coingate and they are willing to give a refund for the order. They are requesting an address to receive the refund.

**Comment by adinetech** [comment]
No, he urged me to refund so I sent MYST from my personal wallet so I'm closing this issue.
