### ISSUE TITLE
dVPN app window isn't displayed with correct form after moving from screen to screen

### ISSUE THREAD

**Issue by lusine-h** [mysteriumnetwork/mysterium-vpn-desktop#323]
**Describe the bug**
After opening the application window on the main screen I moved it to the larger screen the first one, and the window is displayed with incorrect form and size.

**Steps to reproduce**
1. Open the app on the screen with a 1536 x 865 resolution
2. Drag and drop the app window from screen to screen with 1920x1080 resolution

**Expected result**
The app window is displayed with the correct sizes as displayed on the first screen.

**Actual result**
The app window is displayed with the incorrect sizes.

**Desktop**
 - OS: Windows 11
 - App Version 10.8.0

**Video recording**

https://user-images.githubusercontent.com/60058956/160781038-8530b9bb-bf42-4e86-b497-471b7e36e80c.mp4

**Comment by tadaskay** [comment]
Fixed by https://github.com/mysteriumnetwork/mysterium-vpn-desktop/pull/329
