### ISSUE TITLE
Lost Identity right after top up

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/mysterium-vpn-desktop#330]
Today i bought your services but your app stopped working immediately after that so i uninstalled it. So, I download that again and i want able to login into my account because i didn't have my back up key. The transaction was made today from my card I didnt make my backup code and delete the app, because the app bugged out. 
<img width="531" alt="Screenshot 2022-04-05 at 08 51 47" src="https://user-images.githubusercontent.com/84313603/161748056-91ac457d-a60b-4bc5-b82f-180f0245e2c3.png">

Please help me restore my account

**Comment by adinetech** [comment]
It's not something to help after topup the user will be warned to download the identity backup but the user just ignored and lost the funds.

**Comment by isaackielma** [comment]
Not in this case. The app was freezing after payment and the user restarted app. After doing so his identity automatically changed.

I understand if the user was already using the app and accidentally deleted his identity. However, he never even had the chance to download backup files..

**Comment by isaackielma** [comment]
"I bought your product but when i bought that i got black screen the app was crashing, so i was not able to make the backup. Then i reinstall that and when i open that again i had to buy that again. So i want refund, because i made nothing wrong your app just bugged me."
