### ISSUE TITLE
Mysterium VPN Hangs on Starting Daemon Screen On Linux

### ISSUE THREAD

**Issue by 0xvividmirage** [mysteriumnetwork/mysterium-vpn-desktop#335]
**Describe the bug**
After installing Mysterium VPN using both the dpkg -i debfile.deb and/or the apt install ./debfile.deb method, and then running MystweriumVPN, the program just hangs indefinitely in the "Starting Daemon" screen.

**To Reproduce**
1. installing Mysterium VPN using both the dpkg -i debfile.deb and/or the apt install ./debfile.deb method
2. Run "mysterium-vpn-desktop" in the terminal
3. hangs indefinitely in the "Starting Daemon" screen.

**Expected behavior**
Proceeds with running the VPN.

**Logs**
[main.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/8476921/main.log)
[renderer.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/8476922/renderer.log)

**Screenshots**
![Screenshot from 2022-04-12 18-24-44](https://user-images.githubusercontent.com/41744832/163064738-b40d5daa-f7c1-4578-b9bb-d31d38bd874a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - App Version: mysterium-vpn-desktop_10.9.0_amd64.deb

**Additional context**
I have already tried deleting log files and rerunning multiple times. It cannot proceed. Also installation produces the following error at the end:
<pre>sudo apt install ./mysterium-vpn-desktop_10.9.0_amd64.deb 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Note, selecting 'mysterium-vpn-desktop' instead of './mysterium-vpn-desktop_10.9.0_amd64.deb'
The following NEW packages will be installed:
  mysterium-vpn-desktop
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/77.6 MB of archives.
After this operation, 350 MB of additional disk space will be used.
Get:1 /home/username/Downloads/mysterium-vpn-desktop_10.9.0_amd64.deb mysterium-vpn-desktop amd64 10.9.0 [77.6 MB]
Selecting previously unselected package mysterium-vpn-desktop.
(Reading database ... 419420 files and directories currently installed.)
Preparing to unpack .../mysterium-vpn-desktop_10.9.0_amd64.deb ...
Unpacking mysterium-vpn-desktop (10.9.0) ...
Setting up mysterium-vpn-desktop (10.9.0) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3+10.0trisquel2) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
gtk-update-icon-cache: The generated cache was invalid.
WARNING: icon cache generation failed
Processing triggers for gnome-menus (3.36.0-1ubuntu1+10.0trisquel1) ...
Processing triggers for bamfdaemon (0.5.3+18.04.20180207.2-0ubuntu2) ...
Rebuilding /usr/share/applications/bamf-2.index...
N: Download is performed unsandboxed as root as file '/home/username/Downloads/mysterium-vpn-desktop_10.9.0_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)</pre>

**Comment by adinetech** [comment]
Remove the following logs and open it again: https://github.com/mysteriumnetwork/mysterium-vpn-desktop/#linux-1

**Comment by davidpgil** [comment]
After deleting the following logs the same issue still persists:
[](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/#linux-1)

**Comment by sj64** [comment]
Aye exact same issue here:
OS: Elementary 5.1.7 (based on Ubuntu 10.04.6 LTS)
App Version: mysterium-vpn-desktop_10.9.0_amd64.deb

doesn't even seem to generate any new logs either...

**Comment by teewhey** [comment]
Similar issues but I'm running on MacBook Pro M1.
A dialog keeps on popping up asking for password to install some helper.
Then it says "No Update Available" and stuck there. Tried rebooting and stuff and still the same. It's a new install.

OS : Mac Monterey 12.3.1
App : 10.9.0

**Comment by isaackielma** [comment]
@teewhey Could we also get your logs for resolution of this issue? It will help us properly diagnose the issue

~/.mysterium/logs/mysterium-node.log

**Comment by isaackielma** [comment]
COuld you please also try deleting app altogether and then downloading newest version of the app?

**Comment by adinetech** [comment]
Check myst daemon, it will return live logs.

**Comment by adinetech** [comment]
`cd /Applications/MysteriumVPN.app/Contents/MacOS/`
`./MysteriumVPN myst daemon`

**Comment by davidpgil** [comment]
I don't see this issue anymore in Ubuntu 20.04. It no longer hangs and I can use the VPN.
