### ISSUE TITLE
Opening vpn and it sends me straight to top up i cant import my backup key from my first computer

### ISSUE THREAD

**Issue by zusts** [mysteriumnetwork/mysterium-vpn-desktop#337]
**Describe the bug**
-on my first pc when i downloaded the vpn it chose to import the backup key and now when i open it on my second pc it sends me straight to top up

**To Reproduce**
3. See error

**Expected behavior**
id expect to open up and see import backup key not top up
**Logs**
Attach logs (app, node, supervisor) to the issue. Where to find the logs: https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logs

**Screenshots**

**Desktop (please complete t
[main.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/8552457/main.log)
[renderer.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/8552458/renderer.log)
![Screenshot_16](https://user-images.githubusercontent.com/104346826/165040331-086d2c9c-bc1b-45c0-9e88-a96d1506e1ee.png)
he following information):**
 - OS: [e.g. Windows 10]
 - App Version [e.g. 4.1.0]

**Additional context**

**Comment by isaackielma** [comment]
It looks like an Identity is already in use. If you do not have any balance on that identity and would like to delete it, you can run `RD /S %HOMEDIR%\.mysterium` on command prompt. Then, open the app again and you should see the back up button
