### ISSUE TITLE
“You already have enough funds to register”

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/mysterium-vpn-desktop#340]
Getting the error “You already have enough funds to register” when I attempt to top up, even though I have 0 MYST left.

<img width="798" alt="Screenshot 2022-05-04 at 04 42 26" src="https://user-images.githubusercontent.com/84313603/166640641-c855cfd3-44b2-450e-88b8-ccd455421e66.png">

**Comment by tadaskay** [comment]
Please add more context to this issue, such as:
- Steps to reproduce
- Identity
- Logs

**Comment by isaackielma** [comment]
- Proceed with regular credit card top up 
- 0xb4010bc72342e73afab6b1768351f932bd9564c4
-https://mystnodes.com/support/logs/2022-05-09-54cc28de-c28a-4a4d-92e0-135a3990b26d-mysterium-node.zip2753257201
