### ISSUE TITLE
Mysterium Desktop app is not listing the nodes

### ISSUE THREAD

**Issue by adinetech** [mysteriumnetwork/mysterium-vpn-desktop#362]
**Describe the bug**
The Mysterium Desktop app is not listing the nodes, but https://discovery.mysterium.network/api/v3/proposals is reachable.

**Expected behavior**
It should show all countries and the number of nodes

**Screenshots**
<img width="632" alt="image" src="https://user-images.githubusercontent.com/68943180/175780590-40ec5f92-290f-4365-9a7e-626637ef3581.png">

**Desktop (please complete the following information):**
 - OS: macOS 12 Monterey, Windows 10
 - App Version: macOS: 10.11.0, Windows: 10.11.1
 
 **Additional context**
 Few users and I'm personally facing the same issue in the versions 10.11.0 and 10.11.1

**Comment by Peter-SovietSquirrel** [comment]
Logs submitted #7613

**Comment by abdullahrafi882** [comment]
Also issue nodes are not showing, sometimes it's showing & sometimes not showing..  report id : 7636

![image](https://user-images.githubusercontent.com/59306574/175969620-16629dc4-538e-4ec2-809a-e531a4d064f7.png)

**Comment by abdullahrafi882** [comment]
report id " 7632

**Comment by adinetech** [comment]
Mysterium identity of the user: 0x1e5ba19d546a2b152e081105f048bc0d2bdc03ac
