### ISSUE TITLE
Issue with Upgrading identity compatibility **Failed to upgrade ID (restart and try again)**

### ISSUE THREAD

**Issue by rahimche** [mysteriumnetwork/mysterium-vpn-desktop#377]
Hi
when I tried to restore my wallets, it makes an upgrade of identity compatibility 
the program restart and try to make this upgrade
after a while I got this message : **"Failed to upgrade ID (restart and try again)"**

![294753956_301783555464472_8933609762480496177_n](https://user-images.githubusercontent.com/100769875/180827667-4b4d4fe5-d17c-45a9-9690-0b2a62fccb24.jpg)

I tried in different machine again and again but nothing is happening
Please help me to fix this 
My IDs : 
0x8051000bbb32a60302db15b48eb2153d52336a89
0x3f5516b9aee37cdd3bdafe044cb33b39a172b56a
PS: I have more than 1000 myst in those wallets

**Comment by isaackielma** [comment]
Which version of the app are you using? How long have you had these identities for? And how did you manage to accumulate 1000 myst in those wallets?

Sorry about this inconvenience, we will find reason for the issue and resolve it ASAP

**Comment by rahimche** [comment]
I have the latest version
I had those identities for more than 6 months
I bought those myst when it was cheaper
----
plz help
