### ISSUE TITLE
New VPN User. MacOS 10.13.6 Stuck on the Top Up screen [bug]

### ISSUE THREAD

**Issue by grafburin** [mysteriumnetwork/mysterium-vpn-desktop#380]
**Describe the bug**
I am not able to get past the Top Up / Enter Referral Code screen. I've topped up twice (each time $3.99) using crypto (receipts provided to Isaac on help@mysterium.network) thinking that the payment didn't go through. Then I uninstalled and reinstalled the software. Still no luck.

**To Reproduce**
1. Download MysteriumVPN-10.12.4-universal.dmg from the https://www.mysteriumvpn.com/download
2. Double click MysteriumVPN-10.12.4-universal.dmg
3. In the window that opens drag the Mysterium file to Applications. Wait until it copies.
4. Run Mysterium VPN
![Screen Shot 2022-07-29 at 12 34 56 AM](https://user-images.githubusercontent.com/110218062/181690176-68f1382c-679a-4e84-b353-e82ee26924ed.png)

5. Go through the series of welcome screens
6. Arrive at the Your Wallet screen
7. There's no sign of 2x$3.99 that I paid and I can't get to the next screen to register.

**Expected behavior**
See $7.98 in the wallet and be able to use the VPN.

**Logs**

**Screenshots**
See attached.

**Desktop (please complete the following information):**
 - MacOS 10.13.6
 - Mysterium VPN App 10.12.4

**Additional context**
![Screen Shot 2022-07-29 at 12 34 56 AM](https://user-images.githubusercontent.com/110218062/181690224-a284f11a-7154-452f-9d7f-b7d4918ad361.png)

**Comment by daamiian** [comment]
same thing on windows for me

**Comment by daamiian** [comment]
Honestly what is this project? It seems like nothing ever gets fixed.

**Comment by revunix** [comment]
Same here... still not fixed

**Comment by isaackielma** [comment]
Please download newest app version manually instead, it should work then:https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/
