### ISSUE TITLE
Could not create p2p channel during connect: p2p dialer failed: timeout while performing configuration exchange Stage:connection_unknown_error}

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/mysterium-vpn-desktop#387]
I have set up the program on UBUNTU 22.04 and whilst a few servers will connect, i am getting the following error on most connections:

Error:could not create p2p channel during connect: p2p dialer failed: timeout while performing configuration exchange Stage:connection_unknown_error}
2022-08-11T15:18:02.706 WRN ../../core/quality/sender.go:403 > Can't recover session context error="unknown session: "
2022-08-11T15:18:02.706 ERR ../../tequilapi/endpoints/connection.go:203 > Failed to connect error="could not create p2p channel during connect: p2p dialer failed: timeout while performing configuration exchange"
2022-08-11T15:18:02.706 WRN ../../core/quality/sender.go:403 > Can't recover session context error="unknown session: "

*_More log info can be sent upon request_

App Version: 10.13.2 (also tried an older 10.11 release)
We have done testing on Windows PC and it works fine. Issue only happening on Linux
<img width="583" alt="Screenshot 2022-08-23 at 13 01 58" src="https://user-images.githubusercontent.com/84313603/186206887-ae749d0f-4d95-43ff-9e9a-2e25a7192f61.png">

**Comment by punch1982** [comment]
<img width="201" alt="Screenshot at Aug 23 17-08-17" src="https://user-images.githubusercontent.com/19227983/186207944-fea760cb-7fc1-4712-935e-9cb45620c1a5.png">

This is the error seen from the GUI also

**Comment by punch1982** [comment]
This remains the case on any Ubuntu/Debian box - I've tried multiple versions and only certain servers connect. On the Windows or macOS versions, the same servers that fail on Ubuntu/Debian work fine

**Comment by isaackielma** [comment]
Have you tried different internet connection by any chance?

**Comment by jitneyy** [comment]
i dont have a diff internet

**Comment by punch1982** [comment]
same for me sadly - I only have home internet and my mysterium is on a VM there. As I said though, I've tried many versions of Ubuntu/Debian etc and all the same error(s). On macOS or Windows they're fine.

**Comment by jitneyy** [comment]
make sure your not connected to a vpn while using mysterium / restart pc fixed it for me

**Comment by punch1982** [comment]
I've tried that - this is specific to ubuntu/debian - I've tried many versions and all the same. MacOS all fine.

**Comment by punch1982** [comment]
Just updated to 10.14.2 and this seems much better. The errors I was seeing before aren't there and I'm able to connect to all tested servers. Whatever has been added to this update seems to now make UBUNTU/DEBIAN work much better. :)
