### ISSUE TITLE
Flatpaks and Snaps

### ISSUE THREAD

**Issue by tonypachino** [mysteriumnetwork/mysterium-vpn-desktop#388]
Can you please make flatpak or snap packages for your app?

**Describe the solution you'd like**
so that we can use it on any linux distribution.

**Comment by veldspar** [comment]
you can actually use it on any linux distribution - either compile from source or unpack the deb package and copy the file system tree from inside it into your filesystem tree. make sure you have sudo, as well as the wireguard and tun kernel modules installed or built into your kernel.

**Comment by un3481** [comment]
> you can actually use it on any linux distribution - either compile from source or unpack the deb package and copy the file system tree from inside it into your filesystem tree. make sure you have sudo, as well as the wireguard and tun kernel modules installed or built into your kernel.

yes, I could do all of those things, but flatpak is still better
