### ISSUE TITLE
Connecting to the supervisor... over and over.

### ISSUE THREAD

**Issue by chrisooo3** [mysteriumnetwork/mysterium-vpn-desktop#396]
Hi, 
I am trying to start the mysterium-vpn-desktop on ubuntu lts(started on virutal machine).
When I run `yarn dev`, this message appears: `Connecting to the supervisor...` over and over. 
How can I solve this?

I would like to add that there is no socket called  `cd /var/run/myst.sock` on my system.
![image](https://user-images.githubusercontent.com/70841270/189604279-8765c6dc-83a1-41c7-a41e-9239218f4636.png)

**Comment by isaackielma** [comment]
[chrisooo3](https://github.com/chrisooo3) Are you still experiencing this same issue?

**Comment by ChiRoXP** [comment]
@isaackielma 
I am now experiencing this problem. 
For further details on my installation, look at issue #468.
