### ISSUE TITLE
After clicking connect -> the app hangs and refreshes

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/mysterium-vpn-desktop#4]
- Select node provider -> click Connect
- Screen "Working on it..." appears, after couple seconds the mouse spinner appears (the app hangs)
- Then the app "refreshes" and user gets the same list of node providers (no connection happened).

Error message:
Could not connect Request failed with status code 417 (path="connection")

cc @tadaskay

**Comment by chompomonim** [comment]
App is in active alpha development. There can be moments when in master you'll find some errors. Please just `git pull -r` and try again.

**Comment by cvl** [comment]
I understand this in alpha, but I guess that the main functionality should work already? I'm sure it works on @tadaskay pc, isn't it?

**Comment by cvl** [comment]
Fixed with today's update, thanks!
