### ISSUE TITLE
I bought this vpn after buying it with crypto time was zero, 10 minutes passed, nothing happened, I closed the program, opened it again, the first page of the program appears again.

### ISSUE THREAD

**Issue by raminsnt** [mysteriumnetwork/mysterium-vpn-desktop#407]
**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Logs**
Attach logs (app, node, supervisor) to the issue. Where to find the logs: https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logs

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - App Version [e.g. 4.1.0]

**Additional context**

**Comment by raminsnt** [comment]
There was no error. It got stuck on this page while I had paid. I closed the program and opened it again, it comes back from the first page of the program. https://drive.google.com/file/d/113VTAPAfkokHHcFTjrhAuHfToFdDWrVW/view?usp=share_link

**Comment by isaackielma** [comment]
Could you please send us your payment receipt here? What was the payment method used? Please share this info with us so we can continue resolving the issue. Thanks!

**Comment by isaackielma** [comment]
Latest update from Coingate reveals refund was already processed. I will close this issue for now and in case user reports otherwise I will reopen the issue

```
Hi,
 
Thanks for contacting CoinGate!
 
I have checked this order and can confirm that refund was requested by the client and issued already. 
 
Please check the confirmation here: https://pay.coingate.com/invoice/ad8d6ad4-0ac2-4336-9deb-609b75036f8e
 
Let me know if you have any other questions. 
 
Regards,
Emilia D.
```

**Comment by raminsnt** [comment]
I can not connect to any connection(node)!!!! 
this is the error:
Failed to connect .could not create p2p channel during connect.p2p dialer failed. could not dial p2p channel could not ping peer too few connections were built

**Comment by raminsnt** [comment]
this is the error:
Failed to connect .could not create p2p channel during connect.p2p dialer failed. could not dial p2p channel could not ping peer too few connections were built
