### ISSUE TITLE
[bug] Unable to install

### ISSUE THREAD

**Issue by RinnDog** [mysteriumnetwork/mysterium-vpn-desktop#411]
![image](https://user-images.githubusercontent.com/90881580/200184129-9aec3cfd-7fb8-4b9c-b87b-6268fc04e329.png)

**Comment by RinnDog** [comment]
![image](https://user-images.githubusercontent.com/90881580/200184218-e64a161f-a898-4b77-b139-645d6c8731ef.png)
Pressed okay and still get looped

**Comment by isaackielma** [comment]
Please download newest app version manually instead, it should work then:https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/
