### ISSUE TITLE
add possibility to filter "Residential" nodes only

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/mysterium-vpn-desktop#412]
**Is your feature request related to a problem? Please describe.**
Currently when someone connects via quick connect they can end up connecting to any node. However, some users would prefer to quick connect to residential nodes only, rather than any node

**Describe the solution you'd like**
Add a filter that can allow for selection of residential nodes only. That way quick connect would only be connecting to "R" nodes.

**Describe alternatives you've considered**
Either the solution above, or we could come up with a way to filter quick connect preferences from settings.

**Comment by veldspar** [comment]
hey, AFAIR if you click "Media Streaming" on the left hand of the desktop client it will only show residential nodes. if you quick connect after that you should always end up with a residential node
