### ISSUE TITLE
[bug] Mysterium Supervisor does not start 10.13.3, Windows 10

### ISSUE THREAD

**Issue by tedwardd** [mysteriumnetwork/mysterium-vpn-desktop#413]
**Describe the bug**
Mysterium 10.13.3 gets stuck in the startup screen loop. The main.log indicates that it is trying to connect to the supervisor. The supervisor log shows the following error:
```
ERR Could not listen pipe on \\.\pipe\mystpipe error="error listening: open \\\\.\\pipe\\mystpipe: The system cannot find the path specified."
```
This appears to be a recurring issue as seen previously (and supposedly fixed) in #144 but now, instead of showing that it's stuck "starting daemon" the Mysterium start screen shows "no update available" with the loading loop.

**To Reproduce**
1. Install Mysterium v10.13.3 on Windows 10
2. Try to start it
3. Confirm myst_supervisor.exe is running
4. Verify error in myst_supervisor.log

**Expected behavior**
Myst Supervisor should start and the client should be able to establish a connection

**Logs**
https://gist.github.com/tedwardd/8ff9dd2af04a4e6ccac8db6a15725654

**Screenshots**
![image](https://user-images.githubusercontent.com/524645/203194986-b290d63c-2cd6-416a-afc0-bdb778ebfbab.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 19045.2311
 - App Version: 10.13.3

**Additional context**

**Comment by isaackielma** [comment]
Please download newest app version manually instead, it should fix the issue: https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/
