### ISSUE TITLE
Cant Connect to any Country

### ISSUE THREAD

**Issue by igotthings56** [mysteriumnetwork/mysterium-vpn-desktop#418]
![image](https://user-images.githubusercontent.com/117814237/206171745-e728c19e-722d-4532-866e-258f98770946.png)
I have only discovered this issue after the latest update.

**Comment by isaackielma** [comment]
Can you please submit your app logs so we could investigate this further with our engineering team? 

 

Access the "Help" tab section on the title bar (top of app window). Then, 'Report Bug'.

 

_Please note  that description and application logs will be attached to the issue. Logs may include sensitive information, such as IP address and location. It will be only accessible and used by the engineering team to address the issue you are reporting._

 

After doing so, please let us know here so we can forward logs to our engineers for further resolution of the issue!

**Comment by isaackielma** [comment]
Have you tried connecting from different network (wifi, mobile data)?

**Comment by igotthings56** [comment]
its fine now, i connected to ukraine and it worked.
