### ISSUE TITLE
[Error] Oops, Could not connect error

### ISSUE THREAD

**Issue by igotthings56** [mysteriumnetwork/mysterium-vpn-desktop#422]
![image](https://user-images.githubusercontent.com/117814237/207875186-ddc44bbf-802d-4f78-a39b-83595e034437.png)
Any fixes?

**Comment by isaackielma** [comment]
Can you please submit your app logs so we could investigate this further with our engineering team? 

 

Access the "Help" tab section on the title bar (top of app window). Then, 'Report Bug'.

 

Please note  that description and application logs will be attached to the issue. Logs may include sensitive information, such as IP address and location. It will be only accessible and used by the engineering team to address the issue you are reporting.

 

After doing so, please let us know here so we can forward logs to our engineers for further resolution of the issue!
