### ISSUE TITLE
daemon retard (can i say retard hear?)

### ISSUE THREAD

**Issue by jitneyy** [mysteriumnetwork/mysterium-vpn-desktop#423]
**Describe the bug**
stuck on daemon
**To Reproduce**
1. Go to 'the download'
2. Click on 'reinstall'
3. See error

**Expected behavior**
dosent work
**Logs**
Attach logs (app, node, supervisor) to the issue. Where to find the logs: https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logs

**Screenshots**
![image](https://user-images.githubusercontent.com/120755927/208215307-96386ea6-cda2-4afa-bce9-a44a585c1ddf.png)

**Desktop (please complete the following information):**
 - OS: [windows 11]
 -
 - App Version [not sure]

**Additional context**

**Comment by jitneyy** [comment]
+ with logs i did everying. deleted the folder and did things with logs. i can show my logs if you want but i reisntalled then so theres really no point

**Comment by jitneyy** [comment]
so idk how but it started working all i did was task manager myst_supervisor and closed out of mysterium launched the installer from the mysterium website and while the installer was launching launched mysterium

**Comment by jitneyy** [comment]
![image](https://user-images.githubusercontent.com/120755927/208247364-2c0d5985-09fd-4f60-8d0e-70bb97a16dd2.png)
 im getting this now

**Comment by jitneyy** [comment]
nvm its happening agian

**Comment by isaackielma** [comment]
Which version of the app do you have downloaded? Make sure you are running latest version of the app

**Comment by jitneyy** [comment]
latest
