### ISSUE TITLE
cant connect to servers

### ISSUE THREAD

**Issue by jitneyy** [mysteriumnetwork/mysterium-vpn-desktop#425]
**Describe the bug**
cant connect to proxies
**To Reproduce**
1. Go to 'idk'
2. Click on 'idk'
3. See error

**Expected behavior**
wont let you connect

**Logs**
Attach logs (app, node, supervisor) to the issue. Where to find the logs: https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logs

**Screenshots**
![image](https://user-images.githubusercontent.com/120755927/208247726-134259dd-ffeb-4ecd-b56d-78ec100b337b.png)

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - App Version idk

**Additional context**

**Comment by TimaHappy** [comment]
I have same problem
