### ISSUE TITLE
Ubuntu cannot establish vpn connection

### ISSUE THREAD

**Issue by dillfrescott** [mysteriumnetwork/mysterium-vpn-desktop#426]
**Describe the bug**
It just throws an error when trying to connect.

**Expected behavior**
I'd expect it to be able to establish the connection...

**Logs**
[main.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/10254588/main.log)
[renderer.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/10254589/renderer.log)
[mysterium-node.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/10254591/mysterium-node.log)
[myst_supervisor.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/10254593/myst_supervisor.log)

**Screenshots**

![Screenshot_20221217_235815](https://user-images.githubusercontent.com/56714680/208318308-ff9f872e-c473-44a4-87ec-771bd59c301a.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.10
 - App Version 10.14.2

**Additional context**
Tried it with and without wireguard installed to no avail...

**Comment by isaackielma** [comment]
Could you please try setting the dns settings to system in app settings?

**Comment by dillfrescott** [comment]
New install of Ubuntu, installed Mysterium VPN fresh. I changed the settings to match what you show in the picture.

Still the same error.
