### ISSUE TITLE
[bug] Payment message is silly

### ISSUE THREAD

**Issue by hiiamboris** [mysteriumnetwork/mysterium-vpn-desktop#428]
**Describe the bug**

![](https://i.gyazo.com/7a894954031745536ec088649e11e4de.png)
This does tell me that BSC-20 chain is not accepted, but does not tell me _what chain is accepted_.
I would guess ERC-20 ? That would be great to pay $5-10 fees for $2 transfer :)
Although most used with USDT is TRC-20 network. Maybe that's the case?

**Expected behavior**

Clear indication of the chain expected.

**Comment by isaackielma** [comment]
Thanks so much for the heads up. Will discuss this with the team!

**Comment by isaackielma** [comment]
Message has been improved for latest release of the app
