### ISSUE TITLE
Oops! could not connect

### ISSUE THREAD

**Issue by AbderrahimOxy** [mysteriumnetwork/mysterium-vpn-desktop#433]
whenever i try to connect it gives me this message:

Oops! could not connect
Failed to connect: could not start new connection: failed to start connection endpoint:
could not configure device: failed to create wg interface: failed to create TUN device myst: could not set MTU for tunnel: 'powerhell - command netsh interface ipv4 set subinterface "myst" mtu=1420 store=presistent': exit status 1 output: the win32 internal error "no process is on the other end of the pipe" 0xE9 

someone advised me to download and install wireguard manually but doesn't work.
I have just downloaded the software on my pc today and this is my first time using it.
Windows 10 x64

**Comment by isaackielma** [comment]
Hello there!

Could you please try installing: https://www.wintun.net/

then, move the dll file to the directory of Mysterium dVPN.

After that, restart the app (in case issue persists)> make a backup and delete the app > Reinstall app

**Comment by InfinitePower563** [comment]
> Hello there!
> 
> Could you please try installing: https://www.wintun.net/
> 
> then, move the dll file to the directory of Mysterium dVPN.
> 
> After that, restart the app (in case issue persists)> make a backup and delete the app > Reinstall app

What is the location of the mysterium dvpn directory?
