### ISSUE TITLE
[bug] Can't connect to VPN

### ISSUE THREAD

**Issue by qq2492802** [mysteriumnetwork/mysterium-vpn-desktop#440]
**Describe the bug**
I try connecting to any vpn location and it gives me an error.

**To Reproduce**
1. Go to Mysterium VPN Application
2. Click on All nodes > Quick Connect > Error

**Expected behavior**
To connect to the VPN.

**Logs**
[main.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/10575655/main.log)
[renderer.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/10575656/renderer.log)

**Screenshots**
![Screenshot_3](https://user-images.githubusercontent.com/123988341/216516259-2daada23-0b98-4e6f-b009-0326bdc72114.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - App Version: 10.14.4

**Comment by BrahimRZG** [comment]
I have the same problem. If you find a solution please leave a comment here. I will inform you if I got a solution.  Thanks in advance

**Comment by qq2492802** [comment]
> 

Hey there! Thanks for responding about the issue. I've had the same problem and tried reaching out to Mysterium, but the emails I got back were pretty unhelpful. I even popped into their discord server to see if anyone there could help, but no luck there either. If you happen to find a solution, definitely let me know. I'll do the same if I come across anything that might help. Thanks!

**Comment by xjestersdeadx** [comment]
What worked for me on a Mac is the clean install instructions. https://github.com/mysteriumnetwork/mysterium-vpn-desktop/wiki/Clean-install

Not sure if that will help or not.
