### ISSUE TITLE
[BUG] Failed to connect to node due to Interface issue

### ISSUE THREAD

**Issue by EnTaroKerrigan** [mysteriumnetwork/mysterium-vpn-desktop#444]
OS: gentoo

Source Compiles but the VPN itself doesn't work. 
Regular WireGuard VPN works without any issue but not with myst vpn client.
The tools set and library should be there. 
To debug this. please help me to understand how the client code interface with OS ????
Sorry for my terrible understanding about Typescript. 

Screenshot:
![image](https://user-images.githubusercontent.com/71719505/222411318-fce3751a-0ca4-45c2-8f86-e992a0e41dcd.png)

Package Version:
Node.js v16.18.1 (14 LTS failed to compile)
Yarn 1.22.19
npm 8.19.2

LOG:
console output from building to running .
pre-compiled binary shows the same error.

mcg@Mirana ~/src/mysterium-vpn-desktop
 % yarn
yarn install v1.22.19
[1/6] Validating package.json...
[2/6] Resolving packages...
[3/6] Fetching packages...
[4/6] Linking dependencies...
warning " > qrcode.react@2.0.0" has incorrect peer dependency "react@^16.3.0 || ^17.0.0".
warning "react-hot-toast > goober@2.1.8" has unmet peer dependency "csstype@^3.0.10".
warning " > react-table@7.7.0" has incorrect peer dependency "react@^16.8.3 || ^17.0.0-0".
warning " > react-virtualized-auto-sizer@1.0.6" has incorrect peer dependency "react@^15.3.0 || ^16.0.0-alpha || ^17.0.0".
warning " > react-virtualized-auto-sizer@1.0.6" has incorrect peer dependency "react-dom@^15.3.0 || ^16.0.0-alpha || ^17.0.0".
warning " > electron-webpack-ts@4.0.1" has incorrect peer dependency "typescript@^3.8.3".
[5/6] Building fresh packages...
[6/6] Cleaning modules...
Done in 41.01s.
mcg@Mirana ~/src/mysterium-vpn-desktop
 % yarn build
yarn run v1.22.19
$ electron-webpack
Hash: 9896745e0977193d15e41f0b760b3bf8e4aecf3b
Version: webpack 4.46.0
Child
    Hash: 9896745e0977193d15e4
    Time: 21732ms
    Built at: 03/19/2023 10:42:53 AM
          Asset      Size  Chunks                   Chunk Names
        main.js  16.9 KiB       0  [emitted]        main
    main.js.map  17.6 KiB       0  [emitted] [dev]  main
    Entrypoint main = main.js main.js.map
     [0] external "electron" 42 bytes {0} [built]
     [1] ./package.json 5.7 KiB {0} [built]
     [2] external "mysterium-vpn-js" 42 bytes {0} [built]
     [3] external "os" 42 bytes {0} [built]
     [4] external "electron-updater" 42 bytes {0} [built]
     [5] external "pushy-electron" 42 bytes {0} [built]
     [6] external "semver" 42 bytes {0} [built]
     [7] external "path" 42 bytes {0} [built]
     [8] external "@mysteriumnetwork/node" 42 bytes {0} [built]
    [10] external "electron-log" 42 bytes {0} [built]
    [11] external "node-machine-id" 42 bytes {0} [built]
    [12] external "@sentry/electron" 42 bytes {0} [built]
    [17] multi ./src/main/index.tsx 28 bytes {0} [built]
    [18] external "electron-devtools-installer" 42 bytes {0} [built]
    [19] ./src/main/index.tsx + 19 modules 37.5 KiB {0} [built]
         | ./src/main/index.tsx 9.41 KiB [built]
         | ./src/config.ts 374 bytes [built]
         | ./src/shared/errors/sentry.ts 438 bytes [built]
         | ./src/shared/log/log.ts 476 bytes [built]
         | ./src/utils/env.ts 295 bytes [built]
         | ./src/shared/ipc.ts 2.16 KiB [built]
         | ./src/utils/handleProcessExit.ts 734 bytes [built]
         | ./src/main/push/push.ts 1.89 KiB [built]
         | ./src/main/node/supervisor.ts 4.84 KiB [built]
         | ./src/main/tray.ts 2.24 KiB [built]
         | ./src/main/menu.ts 948 bytes [built]
         | ./src/main/node/mysteriumNode.ts 8.04 KiB [built]
         | ./src/main/node/tequila.ts 1.44 KiB [built]
         | ./src/main/cliFlags.tsx 228 bytes [built]
         | ./src/utils/paths.ts 349 bytes [built]
         |     + 5 hidden modules
        + 5 hidden modules
Child
    Hash: 1f0b760b3bf8e4aecf3b
    Time: 24109ms
    Built at: 03/19/2023 10:42:56 AM
                           Asset       Size  Chunks                   Chunk Names
    imgs/welcome-bg--Welcome.png    111 KiB          [emitted]        
                      index.html  265 bytes          [emitted]        
                     renderer.js    761 KiB       0  [emitted]        renderer
                 renderer.js.map    142 KiB       0  [emitted] [dev]  renderer
    Entrypoint renderer = renderer.js renderer.js.map
     [0] external "react" 42 bytes {0} [built]
     [1] external "styled-components" 42 bytes {0} [built]
     [2] external "mobx" 42 bytes {0} [built]
     [3] external "mobx-react-lite" 42 bytes {0} [built]
     [4] external "react-router-dom" 42 bytes {0} [built]
     [5] external "mysterium-vpn-js" 42 bytes {0} [built]
     [8] external "electron" 42 bytes {0} [built]
     [9] external "react-hot-toast" 42 bytes {0} [built]
    [13] external "async-retry" 42 bytes {0} [built]
    [15] ./package.json 5.7 KiB {0} [built]
    [26] external "os" 42 bytes {0} [built]
    [27] external "history" 42 bytes {0} [built]
    [29] external "@sentry/electron" 42 bytes {0} [built]
    [58] multi ./src/app/index.tsx 28 bytes {0} [built]
    [60] ./src/app/index.tsx + 157 modules 453 KiB {0} [built]
         | ./src/app/index.tsx 3.76 KiB [built]
         | ./src/shared/errors/sentry.ts 438 bytes [built]
         | ./src/app/analytics/analytics.ts 3.1 KiB [built]
         | ./src/app/store.ts 11.3 KiB [built]
         | ./src/app/ui-kit/colors.ts 559 bytes [built]
         | ./src/shared/ipc.ts 2.16 KiB [built]
         | ./src/shared/log/log.ts 476 bytes [built]
         | ./src/app/navigation/locations.ts 2.13 KiB [built]
         | ./src/app/navigation/store.ts 5.54 KiB [built]
         | ./src/app/daemon/store.ts 7.19 KiB [built]
         | ./src/app/config/store.ts 6.52 KiB [built]
         | ./src/utils/env.ts 295 bytes [built]
         | ./src/app/analytics/event.ts 880 bytes [built]
         | ./src/app/identity/store.ts 10.6 KiB [built]
         | ./src/app/proposals/store.ts 10.8 KiB [built]
         |     + 143 hidden modules
        + 46 hidden modules
    Child HtmlWebpackCompiler:
         1 asset
        Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
        [0] ./node_modules/html-loader/dist/cjs.js?minimize=false!./dist/.renderer-index-template.html 302 bytes {0} [built]
Done in 25.65s.
mcg@Mirana ~/src/mysterium-vpn-desktop
 % yarn dev
yarn run v1.22.19
$ electron-webpack dev
┏ Renderer -------------------

  ℹ ｢wds｣: Project is running at http://localhost:9080/
  ℹ ｢wds｣: webpack output is served from /
  ℹ ｢wds｣: Content not from webpack is served from /home/mcg/src/mysterium-vpn-desktop/static, /home/mcg/src/mysterium-vpn-desktop/dist/renderer-dll

┗ ----------------------------
┏ Main -----------------------

  Hash: 7fe839dac7c12690f831
  Version: webpack 4.46.0
  Time: 778ms
  Built at: 03/19/2023 10:43:05 AM
    Asset     Size  Chunks             Chunk Names
  main.js  219 KiB    main  [emitted]  main
  Entrypoint main = main.js
  [0] multi ./node_modules/electron-webpack/out/electron-main-hmr/main-hmr ./src/main/index.tsx 40 bytes {main} [built]
  [./node_modules/electron-webpack/out/electron-main-hmr/main-hmr.js] 582 bytes {main} [built]
  [./package.json] 5.7 KiB {main} [built]
  [./src/config.ts] 374 bytes {main} [built]
  [./src/main/cliFlags.tsx] 228 bytes {main} [built]
  [./src/main/index.tsx] 9.41 KiB {main} [built]
  [./src/main/menu.ts] 948 bytes {main} [built]
  [./src/main/node/mysteriumNode.ts] 8.04 KiB {main} [built]
  [./src/main/node/supervisor.ts] 4.84 KiB {main} [built]
  [./src/main/node/tequila.ts] 1.44 KiB {main} [built]
  [./src/main/push/push.ts] 1.89 KiB {main} [built]
  [./src/main/tray.ts] 2.24 KiB {main} [built]
  [./src/shared/errors/sentry.ts] 438 bytes {main} [built]
  [./src/shared/ipc.ts] 2.16 KiB {main} [built]
  [./src/shared/log/log.ts] 476 bytes {main} [built]
      + 27 hidden modules

┗ ----------------------------
┏ Renderer -------------------

  ℹ ｢wdm｣: Hash: 7a6769ca72d024ea8138
  Version: webpack 4.46.0
  Time: 3681ms
  Built at: 03/19/2023 10:43:09 AM
                         Asset       Size    Chunks             Chunk Names
  imgs/welcome-bg--Welcome.png    111 KiB            [emitted]  
                    index.html  368 bytes            [emitted]  
                   renderer.js   3.52 MiB  renderer  [emitted]  renderer
  Entrypoint renderer = renderer.js
  [0] multi (webpack)-dev-server/client?http://localhost:9080 (webpack)/hot/dev-server.js css-hot-loader/hotModuleReplacement ./src/app/index.tsx 64 bytes {renderer} [built]
  [./node_modules/css-hot-loader/hotModuleReplacement.js] 3.05 KiB {renderer} [built]
  [./node_modules/lodash/debounce.js] 5.96 KiB {renderer} [built]
  [./node_modules/normalize-url/index.js] 3.85 KiB {renderer} [built]
  [./node_modules/react-dom/client.js] 619 bytes {renderer} [built]
  [./node_modules/webpack-dev-server/client/index.js?http://localhost:9080] (webpack)-dev-server/client?http://localhost:9080 4.29 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.91 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {renderer} [built]
  [./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {renderer} [built]
  [./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {renderer} [built]
  [./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {renderer} [built]
  [./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {renderer} [built]
  [./src/app/index.tsx] 3.76 KiB {renderer} [built]
      + 252 hidden modules
  Child HtmlWebpackCompiler:
       1 asset
      Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
      [./node_modules/html-loader/dist/cjs.js?minimize=false!./dist/.renderer-index-template.html] 407 bytes {HtmlWebpackPlugin_0} [built]

┗ ----------------------------
┏ Renderer -------------------

  ℹ ｢wdm｣: Compiled successfully.

┗ ----------------------------
┏ Electron -------------------

  Debugger listening on ws://127.0.0.1:5858/80255727-47d1-45be-85cf-62af5c983590
  For help, see: https://nodejs.org/en/docs/inspector

┗ ----------------------------
┏ Electron -------------------

  (node:7732) ExtensionLoadWarning: Warnings loading extension at /home/mcg/.config/Electron/extensions/fmkadmapgofadopljbjfkapdkoienihi:
    Permission 'scripting' is unknown or URL pattern is malformed.
  
  (Use `electron --trace-warnings ...` to show where the warning was created)

┗ ----------------------------
┏ Electron -------------------

  10:43:10.031 › Opening in browser window: http://localhost:9080

┗ ----------------------------
┏ Electron -------------------

  [7732:0319/104310.084324:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed

┗ ----------------------------
┏ Electron -------------------

  [7732:0319/104310.141665:ERROR:extensions_browser_client.cc(61)] Extension Error:
    OTR:     false
    Level:   2
    Source:  chrome-extension://khnfeakjdgphhfehcgboheebjjjpbdmn/build/background.js
    Message: Uncaught TypeError: Cannot read properties of undefined (reading 'registerContentScripts')
    ID:      khnfeakjdgphhfehcgboheebjjjpbdmn
    Type:    RuntimeError
    Context: chrome-extension://khnfeakjdgphhfehcgboheebjjjpbdmn/build/background.js
    Stack Trace: 
      {
        Line:     107
        Column:   1
        URL:      chrome-extension://khnfeakjdgphhfehcgboheebjjjpbdmn/build/background.js
        Function: (anonymous function)
      }

┗ ----------------------------
┏ Electron -------------------

  [7732:0319/104310.142375:ERROR:extensions_browser_client.cc(61)] Extension Error:
    OTR:     false
    Level:   1
    Source:  manifest.json
    Message: Service worker registration failed
    ID:      khnfeakjdgphhfehcgboheebjjjpbdmn
    Type:    ManifestError

┗ ----------------------------
┏ Electron -------------------

  10:43:10.832 › Navigating -> /loading

┗ ----------------------------
┏ Electron -------------------

  10:43:10.839 › APPIMAGE env is not defined, current application is not an AppImage

┗ ----------------------------
┏ Electron -------------------

  10:43:10.896 › Resolved machine ID b8aeb48e5637e9893058c761b1ff222c4ea82a15f2f5cffefa32e0ef013ddb8f

┗ ----------------------------
┏ Electron -------------------

  10:43:11.720 › Pushy registration error The API request failed: The '5f23dc54d4786d7760003a71' _id is not linked to any app on Pushy. Please double-check that an app exists in your Pushy dashboard with this _id.

┗ ----------------------------
┏ Electron -------------------

  [7732:0319/104311.735852:ERROR:CONSOLE(160)] "Electron sandbox_bundle.js script failed to run", source: node:electron/js2c/sandbox_bundle (160)
  [7732:0319/104311.735932:ERROR:CONSOLE(160)] "TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))", source: node:electron/js2c/sandbox_bundle (160)

┗ ----------------------------
┏ Electron -------------------

  10:43:15.839 › Resolving NAT type...

┗ ----------------------------
┏ Electron -------------------

  10:43:15.840 › UserEvent: startup null Client: {
    app_version: '0.0.0-snapshot',
    os: 'linux',
    machine_id: 'b8aeb48e5637e9893058c761b1ff222c4ea82a15f2f5cffefa32e0ef013ddb8f',
    os_version: '6.1.10-gentoo-x86_64'
  }

┗ ----------------------------
┏ Electron -------------------

  10:43:15.843 › [startup] Startup sequence start

┗ ----------------------------
┏ Electron -------------------

  10:43:15.843 › Loading identity

┗ ----------------------------
┏ Electron -------------------

  10:43:15.848 › Update timeout Checking for updates

┗ ----------------------------
┏ Electron -------------------

  10:43:15.849 › Mysterium Node is already running

┗ ----------------------------
┏ Electron -------------------

  10:43:15.855 › [sse message event] state-change {
    "serviceInfo": [],
    "sessions": [],
    "sessionsStats": {
      "count": 0,
      "countConsumers": 0,
      "sumBytesReceived": 0,
      "sumBytesSent": 0,
      "sumDuration": 0,
      "sumTokens": 0
    },
    "consumer": {
      "connection": {
        "status": "NotConnected"
      }
    },
    "identities": [
      {
        "id": "0xedf874ce7c7b2414cb5e7241206901d869cc37dc",
        "registrationStatus": "Registered",
        "channelAddress": "0xE7754dF7a0620e82919E5Bc851802dB28050F0a8",
        "balance": 7650144957239828000,
        "earnings": 0,
        "earningsTotal": 0,
        "balanceTokens": {
          "wei": "7650144957239828538",
          "ether": "7.650144957239828538",
          "human": "7.650144"
        },
        "earningsTokens": {
          "wei": "0",
          "ether": "0",
          "human": "0"
        },
        "earningsTotalTokens": {
          "wei": "0",
          "ether": "0",
          "human": "0"
        },
        "stake": 0,
        "hermesId": "0x80Ed28d84792d8b153bf2F25F0C4B7a1381dE4ab",
        "earningsPerHermes": {}
      }
    ],
    "channels": []
  }

┗ ----------------------------
┏ Electron -------------------

  10:43:15.864 › Using config: {"desktop":{"filters":{"other":{"country":"US"},"preset":{"id":2},"quality":{"include-failed":false,"level":1}},"onboarded":true,"quick-connect":false,"terms-agreed":{"at":"2023-02-10T00:41:58.007Z","version":"0.0.50"}},"terms":{"consumer-agreed":true,"provider-agreed":true,"version":"0.0.50"}}

┗ ----------------------------
┏ Electron -------------------

  10:43:16.854 › Identity loaded: {
    id: '0xedf874ce7c7b2414cb5e7241206901d869cc37dc',
    registrationStatus: 'Registered',
    channelAddress: '0xE7754dF7a0620e82919E5Bc851802dB28050F0a8',
    balance: 7650144957239828000,
    earnings: 0,
    earningsTotal: 0,
    balanceTokens: {
      wei: '7650144957239828538',
      ether: '7.650144957239828538',
      human: '7.650144'
    },
    earningsTokens: { wei: '0', ether: '0', human: '0' },
    earningsTotalTokens: { wei: '0', ether: '0', human: '0' },
    stake: 0,
    hermesId: '0x80Ed28d84792d8b153bf2F25F0C4B7a1381dE4ab',
    earningsPerHermes: {}
  }

┗ ----------------------------
┏ Electron -------------------

  10:43:16.855 › [startup] START

┗ ----------------------------
┏ Electron -------------------

  10:43:16.856 › [startup] WELCOME

┗ ----------------------------
┏ Electron -------------------

  10:43:16.856 › [startup] WELCOME_DONE

┗ ----------------------------
┏ Electron -------------------

  10:43:16.856 › [startup] TERMS

┗ ----------------------------
┏ Electron -------------------

  10:43:16.856 › [startup] TERMS_DONE

┗ ----------------------------
┏ Electron -------------------

  10:43:16.856 › [startup] ONBOARDING_STEPS

┗ ----------------------------
┏ Electron -------------------

  10:43:16.857 › [startup] ONBOARDING_STEPS_DONE

┗ ----------------------------
┏ Electron -------------------

  10:43:16.857 › [startup] IDENTITY_CREATE

┗ ----------------------------
┏ Electron -------------------

  10:43:16.857 › [startup] IDENTITY_CREATE_DONE

┗ ----------------------------
┏ Electron -------------------

  10:43:16.857 › [startup] IDENTITY_UPGRADE

┗ ----------------------------
┏ Electron -------------------

  10:43:16.862 › Migration is not required

┗ ----------------------------
┏ Electron -------------------

  10:43:16.863 › [startup] IDENTITY_UPGRADE_DONE

┗ ----------------------------
┏ Electron -------------------

  10:43:16.863 › [startup] IDENTITY_REGISTER

┗ ----------------------------
┏ Electron -------------------

  10:43:16.863 › [startup] IDENTITY_REGISTER_DONE

┗ ----------------------------
┏ Electron -------------------

  10:43:16.863 › [startup] COMPLETE

┗ ----------------------------
┏ Electron -------------------

  10:43:16.864 › Navigating -> /consumer/proposals/manual-connect

┗ ----------------------------
┏ Electron -------------------

  10:43:18.358 › Resolved NAT type: prcone

┗ ----------------------------
┏ Renderer -------------------

  ERROR in /home/mcg/src/mysterium-vpn-desktop/node_modules/react-countdown/dist/Countdown.d.ts(5,47):
  TS2694: Namespace 'React' has no exported member 'Props'.

┗ ----------------------------
┏ Main -----------------------

  ERROR in /home/mcg/src/mysterium-vpn-desktop/node_modules/react-countdown/dist/Countdown.d.ts(5,47):
  TS2694: Namespace 'React' has no exported member 'Props'.

┗ ----------------------------
┏ Electron -------------------

  10:43:30.009 › UserEvent: manual_connect { country: 'US' } Client: {
    app_version: '0.0.0-snapshot',
    os: 'linux',
    country: 'JP',
    consumer_id: '0xedf874ce7c7b2414cb5e7241206901d869cc37dc',
    machine_id: 'b8aeb48e5637e9893058c761b1ff222c4ea82a15f2f5cffefa32e0ef013ddb8f',
    os_version: '6.1.10-gentoo-x86_64'
  }

┗ ----------------------------
┏ Electron -------------------

  10:43:30.010 › UserEvent: balance_update { balance: 7.650144 } Client: {
    app_version: '0.0.0-snapshot',
    os: 'linux',
    country: 'JP',
    consumer_id: '0xedf874ce7c7b2414cb5e7241206901d869cc37dc',
    machine_id: 'b8aeb48e5637e9893058c761b1ff222c4ea82a15f2f5cffefa32e0ef013ddb8f',
    os_version: '6.1.10-gentoo-x86_64'
  }

┗ ----------------------------
┏ Electron -------------------

  10:43:30.011 › UserEvent: connect_attempt {
    country: 'US',
    provider_id: '0x038b61f830148095b0aa662fe8801e532192667c'
  } Client: {
    app_version: '0.0.0-snapshot',
    os: 'linux',
    country: 'JP',
    consumer_id: '0xedf874ce7c7b2414cb5e7241206901d869cc37dc',
    machine_id: 'b8aeb48e5637e9893058c761b1ff222c4ea82a15f2f5cffefa32e0ef013ddb8f',
    os_version: '6.1.10-gentoo-x86_64'
  }

┗ ----------------------------
┏ Electron -------------------

  10:43:31.194 › [sse message event] state-change {
    "serviceInfo": [],
    "sessions": [],
    "sessionsStats": {
      "count": 0,
      "countConsumers": 0,
      "sumBytesReceived": 0,
      "sumBytesSent": 0,
      "sumDuration": 0,
      "sumTokens": 0
    },
    "consumer": {
      "connection": {
        "status": "Connecting",
        "consumerId": "0xedf874ce7c7b2414cb5e7241206901d869cc37dc",
        "hermesId": "0x80Ed28d84792d8b153bf2F25F0C4B7a1381dE4ab",
        "proposal": {
          "format": "service-proposal/v3",
          "compatibility": 2,
          "providerId": "0x038b61f830148095b0aa662fe8801e532192667c",
          "serviceType": "wireguard",
          "location": {
            "continent": "NA",
            "country": "US",
            "city": "Seattle",
            "asn": 21743,
            "isp": "Atlas Networks Corporation",
            "ipType": "residential"
          },
          "price": {
            "currency": "MYST",
            "perHour": 905665845529633,
            "perHourTokens": {
              "wei": "905665845529633",
              "ether": "0.000905665845529633",
              "human": "0.000905"
            },
            "perGib": 217359802927112000,
            "perGibTokens": {
              "wei": "217359802927112000",
              "ether": "0.217359802927112",
              "human": "0.217359"
            }
          },
          "quality": {
            "quality": 2.0250000000000004,
            "latency": 262.646177,
            "bandwidth": 33.37611,
            "uptime": 23.45
          }
        }
      }
    },
    "identities": [
      {
        "id": "0xedf874ce7c7b2414cb5e7241206901d869cc37dc",
        "registrationStatus": "Registered",
        "channelAddress": "0xE7754dF7a0620e82919E5Bc851802dB28050F0a8",
        "balance": 7650144957239828000,
        "earnings": 0,
        "earningsTotal": 0,
        "balanceTokens": {
          "wei": "7650144957239828538",
          "ether": "7.650144957239828538",
          "human": "7.650144"
        },
        "earningsTokens": {
          "wei": "0",
          "ether": "0",
          "human": "0"
        },
        "earningsTotalTokens": {
          "wei": "0",
          "ether": "0",
          "human": "0"
        },
        "stake": 0,
        "hermesId": "0x80Ed28d84792d8b153bf2F25F0C4B7a1381dE4ab",
        "earningsPerHermes": {}
      }
    ],
    "channels": []
  }

┗ ----------------------------
┏ Electron -------------------

  10:43:31.197 › Navigating -> /consumer/connection

┗ ----------------------------
┏ Electron -------------------

  10:43:39.363 › [sse message event] state-change {
    "serviceInfo": [],
    "sessions": [],
    "sessionsStats": {
      "count": 0,
      "countConsumers": 0,
      "sumBytesReceived": 0,
      "sumBytesSent": 0,
      "sumDuration": 0,
      "sumTokens": 0
    },
    "consumer": {
      "connection": {
        "status": "Connecting",
        "consumerId": "0xedf874ce7c7b2414cb5e7241206901d869cc37dc",
        "hermesId": "0x80Ed28d84792d8b153bf2F25F0C4B7a1381dE4ab",
        "proposal": {
          "format": "service-proposal/v3",
          "compatibility": 2,
          "providerId": "0x038b61f830148095b0aa662fe8801e532192667c",
          "serviceType": "wireguard",
          "location": {
            "continent": "NA",
            "country": "US",
            "city": "Seattle",
            "asn": 21743,
            "isp": "Atlas Networks Corporation",
            "ipType": "residential"
          },
          "price": {
            "currency": "MYST",
            "perHour": 905665845529633,
            "perHourTokens": {
              "wei": "905665845529633",
              "ether": "0.000905665845529633",
              "human": "0.000905"
            },
            "perGib": 217359802927112000,
            "perGibTokens": {
              "wei": "217359802927112000",
              "ether": "0.217359802927112",
              "human": "0.217359"
            }
          },
          "quality": {
            "quality": 2.0250000000000004,
            "latency": 262.646177,
            "bandwidth": 33.37611,
            "uptime": 23.45
          }
        }
      }
    },
    "identities": [
      {
        "id": "0xedf874ce7c7b2414cb5e7241206901d869cc37dc",
        "registrationStatus": "Registered",
        "channelAddress": "0xE7754dF7a0620e82919E5Bc851802dB28050F0a8",
        "balance": 7650144957239828000,
        "earnings": 0,
        "earningsTotal": 0,
        "balanceTokens": {
          "wei": "7650144957239828537",
          "ether": "7.650144957239828537",
          "human": "7.650144"
        },
        "earningsTokens": {
          "wei": "0",
          "ether": "0",
          "human": "0"
        },
        "earningsTotalTokens": {
          "wei": "0",
          "ether": "0",
          "human": "0"
        },
        "stake": 0,
        "hermesId": "0x80Ed28d84792d8b153bf2F25F0C4B7a1381dE4ab",
        "earningsPerHermes": {}
      }
    ],
    "channels": []
  }

┗ ----------------------------
┏ Electron -------------------

  10:43:39.582 › UserEvent: connect_failure {
    country: 'US',
    provider_id: '0x038b61f830148095b0aa662fe8801e532192667c',
    duration: 9571
  } Client: {
    app_version: '0.0.0-snapshot',
    os: 'linux',
    country: 'JP',
    consumer_id: '0xedf874ce7c7b2414cb5e7241206901d869cc37dc',
    machine_id: 'b8aeb48e5637e9893058c761b1ff222c4ea82a15f2f5cffefa32e0ef013ddb8f',
    os_version: '6.1.10-gentoo-x86_64'
  }

┗ ----------------------------
┏ Electron -------------------

  10:43:39.582 › Could not connect: Failed to connect: could not start new connection: failed to start connection endpoint: could not configure device: failed to create wg interface: could not setup network: could not set DNS: exit status 1
  Original message: {"error":{"code":"err_connect","message":"Failed to connect: could not start new connection: failed to start connection endpoint: could not configure device: failed to create wg interface: could not setup network: could not set DNS: exit status 1"},"status":500,"path":"/connection"}

┗ ----------------------------
┏ Electron -------------------

  10:43:39.671 › [sse message event] state-change {
    "serviceInfo": [],
    "sessions": [],
    "sessionsStats": {
      "count": 0,
      "countConsumers": 0,
      "sumBytesReceived": 0,
      "sumBytesSent": 0,
      "sumDuration": 0,
      "sumTokens": 0
    },
    "consumer": {
      "connection": {
        "status": "NotConnected"
      }
    },
    "identities": [
      {
        "id": "0xedf874ce7c7b2414cb5e7241206901d869cc37dc",
        "registrationStatus": "Registered",
        "channelAddress": "0xE7754dF7a0620e82919E5Bc851802dB28050F0a8",
        "balance": 7650144957239828000,
        "earnings": 0,
        "earningsTotal": 0,
        "balanceTokens": {
          "wei": "7650144957239828537",
          "ether": "7.650144957239828537",
          "human": "7.650144"
        },
        "earningsTokens": {
          "wei": "0",
          "ether": "0",
          "human": "0"
        },
        "earningsTotalTokens": {
          "wei": "0",
          "ether": "0",
          "human": "0"
        },
        "stake": 0,
        "hermesId": "0x80Ed28d84792d8b153bf2F25F0C4B7a1381dE4ab",
        "earningsPerHermes": {}
      }
    ],
    "channels": []
  }

┗ ----------------------------
┏ Electron -------------------

  10:43:39.672 › Navigating -> /consumer/proposals

┗ ----------------------------

**Comment by tadaskay** [comment]
Please attach all required logs that are needed for us to investigate the issue.
https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logs

**Comment by EnTaroKerrigan** [comment]
I have attached log into original post
