### ISSUE TITLE
mysterium vpn stuck on starting daemon

### ISSUE THREAD

**Issue by zeyhu** [mysteriumnetwork/mysterium-vpn-desktop#445]
**Describe the bug**
mysterium vpn stuck on starting daemon

**To Reproduce**
1. download mysterium vpn
2. open it
3. error is there!

**Expected behavior**
it should of opened normally

**Logs**
[main.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/10959914/main.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/87945709/224778087-74eeb6f5-657a-4d81-a119-7fd9ebc7b2e5.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - App Version  - 10.14.1

**Comment by Syntex1337** [comment]
lmao mc chetor, still is there any fixes bruh

**Comment by zeyhu** [comment]
can't find any

**Comment by tadaskay** [comment]
Please attach all required logs that are needed for us to investigate the issue.
https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logs

**Comment by Syntex1337** [comment]
still any updates i bought mys vpn and regret it

**Comment by webcommie** [comment]
@zeyhu you didn't post your renderer log, there are two app logs. i'm curious if it looks like mine; i'm having the same issue. 

[main.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/11007011/main.log)
[renderer.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/11007012/renderer.log)
[myst_supervisor.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/11007014/myst_supervisor.log)

**Comment by webcommie** [comment]
This issue has been resolved by a mod in the discord server. Solution is to change your DNS provider to Cloudflare or Google. I switched to Cloudflare and it worked instantly.

**Comment by isaackielma** [comment]
@zeyhu I will be closing the issue as it seems to have been solved. Please let us know here otherwise

**Comment by Syntex1337** [comment]
I STILL cant run it.
