### ISSUE TITLE
STARTING DEAMON FIX PLS

### ISSUE THREAD

**Issue by Syntex1337** [mysteriumnetwork/mysterium-vpn-desktop#446]
**Describe the bug**

**To Reproduce**
1. Go to 'open app'
2. Click on 'create wallet then i click to back nothing happens only says starting daemon wth
3. See error

i cant send logs cuz there isnt
I HAVE GOOD INTERNET
IM USING LATEST VERSION
I HAVE REINSTALL 2TIMES 
AND STILL SAME ERROR WTH

**Comment by tadaskay** [comment]
Logs are required to investigate the issue
