### ISSUE TITLE
Chrome reports installer as virus

### ISSUE THREAD

**Issue by Marfa** [mysteriumnetwork/mysterium-vpn-desktop#448]
Chrome 111.0.5563.111, Windows 11.

When I download the installer from the official website https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/download/10.14.4/MysteriumVPN-Setup-10.14.4.exe Chrome doesn't finish download and marks it as virus.

![image](https://user-images.githubusercontent.com/2509171/227713856-78bef391-a468-4ffc-a13b-09c4c900a8df.png)

**Comment by Marfa** [comment]
KIS 21.3.10.391 (i) also marks installer as suspicious.

![image](https://user-images.githubusercontent.com/2509171/227713954-0aa64037-896f-4cd7-8be2-15489cdd501f.png)

**Comment by si458** [comment]
im having the same issue with norton 
![Screenshot 2023-03-26 174525](https://user-images.githubusercontent.com/765314/227790993-bc15f507-dad4-45ec-aefb-7b62e2ced0b8.png)

**Comment by si458** [comment]
this is still an issue 3 months later, how has a new version ont been released yet?

**Comment by tunisiano187** [comment]
every malware detectors have blocked this VPN for security reasons...
Do you think something is possible to solve it ?

**Comment by si458** [comment]
> every malware detectors have blocked this VPN for security reasons...
> Do you think something is possible to solve it ?

The latest 10.14.5 isn't detected as a virus with Norton for myself now
