### ISSUE TITLE
Mysterium VPN knocks out my internet connection

### ISSUE THREAD

**Issue by chainsoaker** [mysteriumnetwork/mysterium-vpn-desktop#454]
Hi, whenever I connect to mysterium vpn no matter where the location is, and then try and load any website the VPN knocks out my internet on my laptop, showing the no connection icon. In the mysterium  app it shows as "connected" with no errors but loads up requests to the VPN on upload to 1Gbit in data really quickly within a minute or two (most likely showing issues with the connection)

**Comment by isaackielma** [comment]
Hello @chainsoaker ! Thanks for reporting this issue. Could you please provide logs so we can further investigate this issue?

Access the "Help" tab section on the title bar (top of app window). Then, 'Report Bug'.

 
Please note  that description and application logs will be attached to the issue. Logs may include sensitive information, such as IP address and location. It will be only accessible and used by the engineering team to address the issue you are reporting.

 
After doing so, please let us know here so we can forward logs to our engineers for further resolution of the issue!
