### ISSUE TITLE
go back " the screen keep looping for hours- App Stuck

### ISSUE THREAD

**Issue by isaackielma** [mysteriumnetwork/mysterium-vpn-desktop#455]
**Describe the bug**
This is what happens when I press " go back " the screen keep looping for hours and no result,
I want the " import an account " screen

**Expected behavior**
App should load previous page.

**Screenshots**
<img width="633" alt="Screenshot 2023-04-23 at 21 36 23" src="https://user-images.githubusercontent.com/84313603/233876187-4835398a-5614-4721-8a7d-3dfda9ff6ad4.png">
<img width="630" alt="Screenshot 2023-04-23 at 21 36 31" src="https://user-images.githubusercontent.com/84313603/233876188-f0c601b1-0c9b-4e07-8546-5eb7b31ef867.png">

**Desktop (please complete the following information):**
 - OS: Windows
 - App Version : 10.14.4 version

**Additional context**
More troubleshooting will be done by @isaackielma

**Comment by isaackielma** [comment]
**Temporary Solution:**

For MAC: 

1. Close the app:
2. Open Terminal:
3. Run the following command: `rm -rf ~/.mysterium`
4. Reopen the app

For Windows:

1. Close the app
2. Go to file explorer
3. search: %USERPROFILE%\.mysterium\
4. Delete it
5. Reopen app

**or**

-When using CMD:
1. Close the app
2. Open CMD
3. Run the following command: `RD /S %HOMEDIR%\.mysterium`

-When using powershell:
1. Close the app
2. Open powershell
3. Run the following command: `Remove-Item $HOME\.mysterium`

**Comment by chopoalc** [comment]
works perfectly for Mac OS X
Thanks for the help !
