### ISSUE TITLE
[bug]List empty!

### ISSUE THREAD

**Issue by Invettz** [mysteriumnetwork/mysterium-vpn-desktop#458]
**To Reproduce**
1. Open Mysterium VPN
2. VPN list empty

**Expected behavior**
VPN List

**Logs**
Attach logs (app, node, supervisor) to the issue. Where to find the logs: https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logs

[renderer.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/11777581/renderer.log)
[main.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/11777582/main.log)

**Screenshots**

![154833453-99915a2b-7cc5-4e60-b72f-097c5b56dc59](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/assets/136866503/4758f92e-8f5f-4e33-ab2e-1aa2e815b058)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - App Version 10.14.4

**Additional context**

**Comment by Invettz** [comment]
[myst_supervisor.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/11777584/myst_supervisor.log)

**Comment by adinetech** [comment]
Are you able to access this? https://discovery.mysterium.network/api/v4/proposals
