### ISSUE TITLE
[feature request]: Adding official support for gentoo's portage package manager.

### ISSUE THREAD

**Issue by BruhRain** [mysteriumnetwork/mysterium-vpn-desktop#466]
This isn't related to a problem however, getting mysterium to run via .deb packages can prove very annoying as some gentoo packages are named differently, adding official support for gentoo would mean the package would be listed under something like `net-misc/mysterium-vpn` as an example.

It may take a long time to install especially because you're using node v14 and gentoo requires you to build everything from source code instead of using prebuilt binaries.

**Comment by Redo11** [comment]
Honestly an Appimage or Flatpak would be better

**Comment by BruhRain** [comment]
true, i agree, i used flatpak and it seems really awesome
