### ISSUE TITLE
Failed to connect: could not create p2p channel during connect: p2p dialer failed: could not dial p2p channel: could not ping peer: too few connections were built 

### ISSUE THREAD

**Issue by rV4nxZ** [mysteriumnetwork/mysterium-vpn-desktop#467]
**Describe the bug**
Failed to connect: could not create p2p channel during connect: p2p dialer failed: could not dial p2p channel: could not ping peer: too few connections were built.

**To Reproduce**
1. Go to 'Home'
2. Click on 'Connect'
3. See error

**Expected behavior**
Connect to VPN.

**Logs**
[mysterium-node.log](https://drive.google.com/file/d/1Eb26z3QQE7UataMXjoz6pyhPYS7999r-/view?usp=sharing)
[myst_supervisor.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/12011726/myst_supervisor.log)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - App Version [e.g. 10.14.4]

**Additional context**
It let me connect to some servers, but i need to do try and failure continuosly to get on a node.

**Comment by igsergor** [comment]
Failed to connect: could not create p2p channel during connect: p2p dialer failed: could not dial p2p channel: could not ping peer: too few connections were built.
