### ISSUE TITLE
"Authentificating failed. Please try again"

### ISSUE THREAD

**Issue by Nowanehere** [mysteriumnetwork/mysterium-vpn-desktop#478]
Hello, i did a full windows reset today, and i just installed Mysterium again but i'm not able to log in my accoumpt... 

I launch the app, click "sign in mysterium vpn"
Sending me to authentif link, i allow the app to do what's needed etc etc... 
But when it comes back to the app, i just get this message all the time "Authentificating failed. Please try again"

I don't have any logs, and i can only install the google store app... 

 WINDOWS 10 
 APP 1.4.3.0

**Comment by jdroidgit** [comment]
Not sure if it's ok to add this here, but I'm having this issue on a fresh windows install with the same version.
