### ISSUE TITLE
[bug] My location shows Unknown XX

### ISSUE THREAD

**Issue by DodgeCharger69** [mysteriumnetwork/mysterium-vpn-desktop#493]
**Describe the bug**
I not used fro some time maybe for a week. Today try to connect but cant. On bottom instead my ip/location show unknown and when i move mouse there show xx.

**To Reproduce**
Just open.

**Screenshots**
![image](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/assets/32986635/8998b6ea-2d7d-4ad7-be7a-67cb73764baf)
![image](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/assets/32986635/75db489b-c2b5-4f1a-9805-a2728a49a33f)

**Desktop (please complete the following information):**
 - OS:  Windows 10
 - App Version: 10.16.0

**Additional context**
Not work on phone too. But now after 77 trying connected to 1 location but still cant reproduce to connect to either one node.

**Comment by DodgeCharger69** [comment]
> I have the same problem and couldn't find the resolution yet

I think the problem is at them.

**Comment by gir489returns** [comment]
Been an issue for ages, they stopped caring about this app because they don't make anything off their pump and dump MYST token anymore, they've been focusing on the 2.0 app almost exclusively, the desktop client has become almost unusable.
