### ISSUE TITLE
yarn build doesn't add MysteriumVPN2.app to ./deploy/darwin

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/mysterium-vpn-desktop#5]
and then "yarn packer" complains if this file is missing:

>yarn packer
cleaning build directory at /Users/z/app/deploy/darwin/build
creating build directory at /Users/z/app/deploy/darwin/build
(node:72133) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/Users/z/app/deploy/darwin/MysteriumVPN2.app'
(node:72133) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:72133) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

**Comment by chompomonim** [comment]
What yarn version do you use?
