### ISSUE TITLE
Failed to connect: could not create p2p channel during connect: p2p dialer failed: could not dial p2p channel: could not ping peer: too few connections were built #467

### ISSUE THREAD

**Issue by igsergor** [mysteriumnetwork/mysterium-vpn-desktop#506]
**Describe the bug**
[A clear and concise description of what the bug is.](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/issues/467) - it is actual issue - please get it not closed

**To Reproduce**
3. See error

**Expected behavior**

**Logs**
Attach logs (app, node, supervisor) to the issue. Where to find the logs: https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logs

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 10]
 - App Version [e.g. 4.1.0]

**Additional context**

**Comment by Kefpull** [comment]
I've noticed this happens when trying to connect while using T-Mobile Home Internet (rather than my normal cable wifi), it might have something to do with your ISP if it's consistent.

**Comment by rinzler100** [comment]
I have this problem when on my ISP (Spectrum). Hopefully a workaround is created.

**Comment by rinzler100** [comment]
Updating info here, same error is thrown on **multiple devices** and **multiple wallets** (accounts), and happens on **any ISP** (Verizon, T-Mobile, Spectrum home internet, etc.).
