### ISSUE TITLE
mysterium-vpn-desktop version 2.5 can not lanuch on WINDOWS10 stuck at lanuch UI

### ISSUE THREAD

**Issue by googlegame** [mysteriumnetwork/mysterium-vpn-desktop#53]
mysterium-vpn-desktop version 2.5 can not lanuch on WINDOWS10 stuck at lanuch UI

please check the LOG files, 

thanks

[myst_supervisor.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/4963396/myst_supervisor.log)
[renderer.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/4963397/renderer.log)
[main.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/4963398/main.log)

**Comment by tadaskay** [comment]
Need logs from Mysterium node: `~/.mysterium/logs/mysterium-node.log`
https://github.com/mysteriumnetwork/mysterium-vpn-desktop#node

**Comment by chompomonim** [comment]
Have to close this issue as not logs provided and we're already on version 2.8, so. many things could be already changed.
