### ISSUE TITLE
yarn build doesn't add MysteriumVPN2.app to ./deploy/darwin

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/mysterium-vpn-desktop#6]
Please don't close issues before resolving them (https://github.com/mysteriumnetwork/mysterium-vpn-desktop/issues/5#event-3151160388)

Yarn version: 1.22.4

1) After cloning repo, remove MysteriumVPN2.app file from ./deploy/darwin (I believe it shouldn't be in the repo in the first place).
2) Run yarn && yarn build
3) run yarn packer
This produces error
cleaning build directory at /Users/z/app/deploy/darwin/build
creating build directory at /Users/z/app/deploy/darwin/build
(node:72133) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, stat '/Users/z/app/deploy/darwin/MysteriumVPN2.app'
(node:72133) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag --unhandled-rejections=strict (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:72133) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code

**Comment by tadaskay** [comment]
`MysteriumVPN2.app` is a directory that contains configuration for building macOS bundle. Don't remove it from the repo and follow the README instructions.

**Comment by cvl** [comment]
Thanks for the reply.

As this is reference implementation, I'm building Portals app on top of this ref implementation.

If I create another app, yarn packer simply packages the old MysteriumVPN2.app which is present in deploy/darwin/ folder.

I'll create another issue for this then.
