### ISSUE TITLE
Error during installation on Win10x64

### ISSUE THREAD

**Issue by balobilo** [mysteriumnetwork/mysterium-vpn-desktop#68]
![bug10 0 1](https://user-images.githubusercontent.com/16378234/95014176-762b6e80-0645-11eb-8099-4998803e1004.jpg)

**Comment by balobilo** [comment]
I think I could reinstall and run it again, but first i needed to delete MysteriumVPNSupervisor in the registry

**Comment by chompomonim** [comment]
@balobilo which version of app you tried to use?

**Comment by balobilo** [comment]
2.10.1

**Comment by balobilo** [comment]
Right now the App is running and connects sometimes to nodes but runns very unstable and disconnects often

**Comment by chompomonim** [comment]
Could you share logs? Maybe we can find something there...

**Comment by balobilo** [comment]
[mysterium-node.log](https://github.com/mysteriumnetwork/mysterium-vpn-desktop/files/5535915/mysterium-node.log)

**Comment by chompomonim** [comment]
We're not able to reproduce it with newest apps. Please try 3.3+ desktop app, it should work already without issues. If you'll have any issues, please open new issue.
