### ISSUE TITLE
Installation problem on windows 10

### ISSUE THREAD

**Issue by Ammar7347** [mysteriumnetwork/mysterium-vpn-desktop#71]
The installer seems to be bugged for me since I can't install on my PC. The moment I click on 'install', it shows and get stuck on 'Installation Aborted - Setup was not completed successfully.' and the only option is to cancel or close the installer. Please fix this problem.

Things which might help:
- Windows 10 Pro 64 Bit latest
- My HDD failed recently and Mysterium was installed on that failed HDD so in windows add or remove programs list, I can still mysterium installed but can't remove it as it gives me an error.
- There is still mysterium desktop shortcut present without the icon and is inaccessible because of HDD failure.

![image](https://user-images.githubusercontent.com/19525838/99428391-654e6800-2928-11eb-80b0-244ecfce7bc2.png)

**Comment by chompomonim** [comment]
So, you had installed Mysterium on separate hdd and now it is detached. Uninstall or fresh installation doesn't work for you. Right? 

We will try to reproduce some such setup and will check what we can do.

**Comment by Ammar7347** [comment]
> So, you had installed Mysterium on separate hdd and now it is detached. Uninstall or fresh installation doesn't work for you. Right?
> 
> We will try to reproduce some such setup and will check what we can do.

That's correct. I can't uninstall it from windows built-in 'Add or remove programmes' since windows can't detect it and I think due to that I can't do a fresh install as it gets stuck immediately and gives the error. Hoping for a fix soon. Thanks!

**Comment by tomasmik** [comment]
I just tried to reproduce this, following the steps literally. Installed to a different drive, then removed it.

Seems like it's true that you cant remove it using the new `Add or remove programs`  in windows, but you can sort of fix this by simply using the [old Control pane](https://support.microsoft.com/en-us/windows/uninstall-or-remove-apps-and-programs-in-windows-10-4b55f974-2cc6-2d2b-d092-5905080eaf98) to remove the desktop app. I was able to install everything after doing so, could you try that and see if it also fixes it for you?

**Comment by Ammar7347** [comment]
Thank you @tomasmik!

I deleted the app from old apps and programmes under the control panel and now I was able to install the app without any issue.
