### ISSUE TITLE
Open and wait...

### ISSUE THREAD

**Issue by frank-pian** [mysteriumnetwork/mysterium-vpn-desktop#80]
No communication has been established since launching the APP
win10 x64
![QQ截图20210114182009](https://user-images.githubusercontent.com/8214804/104578150-5587a180-5695-11eb-9e77-c2f3a5490441.png)

**Comment by tadaskay** [comment]
Hey. It appears that the node is unable to start in the background. Could you provide the logs from `~/.mysterium/logs/mysterium-node.log`?

**Comment by chompomonim** [comment]
It may be related to #2982

**Comment by frank-pian** [comment]
> 
> 
> It may be related to [mysteriumnetwork/node#2982](https://github.com/mysteriumnetwork/node/issues/2982)

yes, port conflicts

**Comment by tomasmik** [comment]
I assume this should be fixed using the latest release.
