### ISSUE TITLE
Any Plans to support linux??

### ISSUE THREAD

**Issue by peepopoggers** [mysteriumnetwork/mysterium-vpn-desktop#82]
For those using the open sourced linux, it makes sense to use an open sourced decentralized vpn, but this does not support linux natively. Will there be any plans in the future?

E.G: Native .deb etc

**Comment by chompomonim** [comment]
Duplicate of https://github.com/mysteriumnetwork/node/issues/1876

**Comment by chompomonim** [comment]
We also already have Linux CLI, please learn more here:
https://docs.mysterium.network/user-guide/
