### ISSUE TITLE
 china user also can not connect-Oops! Couldn't connect. Try another provider?

### ISSUE THREAD

**Issue by googlegame** [mysteriumnetwork/mysterium-vpn-desktop#87]
hi,
 china user also can not connect-Oops! Couldn't connect. Try another provider?

![image](https://user-images.githubusercontent.com/86212/105791439-10327080-5fc1-11eb-854f-8ac051475d80.png)

![image](https://user-images.githubusercontent.com/86212/105791536-3d7f1e80-5fc1-11eb-8e51-4202dc4b9145.png)

**Comment by chompomonim** [comment]
Hey, I see that you're using not newest version of dVPN app. Could you upgrade to latest version (3.4.2+)?

https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases

**Comment by tadaskay** [comment]
Please attach full logs to the issue as described in https://github.com/mysteriumnetwork/mysterium-vpn-desktop#logging
