### ISSUE TITLE
If (win === null) doesn't catch when win is undefined

### ISSUE THREAD

**Issue by cvl** [mysteriumnetwork/mysterium-vpn-desktop#93]
Got this today:
TypeError: Cannot read property 'show' of undefined
  File "app:///src/main/index.tsx", line 147, in App.<anonymous>

Referring to:
https://github.com/mysteriumnetwork/mysterium-vpn-desktop/blob/1e3e1f4063dee8d822952af7c7d3b00af5235475/src/main/index.tsx#L199

win was probably undefined (not null). === catches only if win is null.

Not sure how to test this activate state (when win is undefined), so it's only an assumption.

Easy fix should be to change to == instead of ===
so if (win == null) {

**Comment by chompomonim** [comment]
@cvl pull requests are welcome.

**Comment by tadaskay** [comment]
Fixed in https://github.com/mysteriumnetwork/mysterium-vpn-desktop/commit/7096aece04b9ff7e17695aba5c015fa1b748f05c
thanks
