### ISSUE TITLE
Open and wait on Mac OS

### ISSUE THREAD

**Issue by mikemfleming** [mysteriumnetwork/mysterium-vpn-desktop#99]
This _may_ be similar to these issues but I'm not sure as they are all reported on Windows.
https://github.com/mysteriumnetwork/mysterium-vpn-desktop/issues/80
https://github.com/mysteriumnetwork/node/issues/2982
https://github.com/mysteriumnetwork/node/issues/2982

### Expected
Download the app from [here](https://mysterium.network/apps/) and connect to nodes while running Mac OS 11.2.1 (Big Sur).

### Actual
The app opens and hangs. Opening the Console app reveals some errors but they're pretty cryptic to me. I think it may have something to do with permissions to that file but I'm not sure if or how I should `chmod` it appropriately. 
* Error 
`MysteriumVPN Helper (GPU): Failed to get cache main folder: failed to lookup DARWIN_USER_CACHE_DIR err:5`
* Warning 
`MysteriumVPN Helper (GPU): access: /var/folders/yq/167nx6zn0dl2qkthbtvlqfhm0000gn/: [1: Operation not permitted]`

<img width="664" alt="Screen Shot 2021-02-22 at 10 28 26 AM" src="https://user-images.githubusercontent.com/14914451/108787777-0c502a80-753c-11eb-9eaa-150734989a6a.png">

**Comment by mikemfleming** [comment]
This _may_ be similar to these issues but I'm not sure as they are all reported on Windows. 
https://github.com/mysteriumnetwork/mysterium-vpn-desktop/issues/80
https://github.com/mysteriumnetwork/node/issues/2982
https://github.com/mysteriumnetwork/node/issues/2982

**Comment by tadaskay** [comment]
Could you try the latest release https://github.com/mysteriumnetwork/mysterium-vpn-desktop/releases/tag/3.7.0 ?

**Comment by mikemfleming** [comment]
Works for me! Thanks for that. Out of curiosity, what was causing the issue?

**Comment by chompomonim** [comment]
@mikemfleming I think it may be related to this fixes mentioned in release notes: 
- Fix broken supervisor version check
- Kill ghost node instances
